### ISSUE TITLE
Calculating price of a lot of bonds

### ISSUE THREAD

**Issue by andhherson** [eddelbuettel/rquantlib#107]
Is it possible to use 'FixedRateBond' to calculate the price of a lot of bonds?

**Comment by eddelbuettel** [comment]
Sure. You may not get efficiency benefits so doing N bonds may just take N times as much as doing one.

**Comment by andhherson** [comment]
Nice! But when I indicate the column with the issuDate and maturity date it returns: Error in FixedRateWithYield(bond, rates, schedule, calc, yield) : expecting a single value

bond <- list(settlementDays=1, issueDate=as.Date(te$NTNF.date.1.10.),
             faceAmount=100, accrualDayCounter='Thirty360',
             paymentConvention='Unadjusted')

schedule <- list(effectiveDate=as.Date(dataframe$NTNF.date),
                 maturityDate=as.Date(dataframe$NTNF.mature),
                 period='Semiannual',
                 calendar='UnitedStates/GovernmentBond',
                 businessDayConvention='Unadjusted',
                 terminationDateConvention='Unadjusted',
                 dateGeneration='Forward',
                 endOfMonth=1)

Thank you

**Comment by tleitch** [comment]
Yes. One at a time.

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up.
