### ISSUE TITLE
UnitedStates/GovernmentBond calendar not accurate?

### ISSUE THREAD

**Issue by adgh** [eddelbuettel/rquantlib#108]
`RQuantLib::isHoliday("UnitedStates/GovernmentBond", as.Date("2017-11-10"))` 

This suggests the day preceding Veteran's Day 2017 was a holiday because Veteran's day fell on a Saturday. This seems to be the logic followed by QuantLib in general, but SIFMA doesn't recommend closure for the day before Saturday veteran's days (2017, 2006, 2000).

**Comment by eddelbuettel** [comment]
Interesting. Do you have some further documentation or examples? 

In any event that is an upstream issue in QuantLib so paging @lballabio as we would need to fix this in QuantLib,

**Comment by lballabio** [comment]
Good news: the issue was fixed in QuantLib 1.12 (see https://github.com/lballabio/QuantLib/pull/329).

**Comment by adgh** [comment]
Sure, QuantLib 1.13 [calendar documentation](https://www.quantlib.org/reference/class_quant_lib_1_1_united_states.html) states: 

> "Veterans' Day, November 11th (moved to Monday if Sunday or Friday if Saturday)"

If you follow the calendar source, you eventually get to [SIFMA](https://www.sifma.org/resources/general/holiday-schedule/). Looking up the history of veteran's day in 2017, 2006, and 2000 shows they don't recommend closure on the Friday if the holiday falls on a Saturday. I'm not sure why the date is missing entirely from 2017 on SIFMA's documentation.

**Comment by lballabio** [comment]
The calendar documentation is out of date (I'll have to fix that) but the code does the right thing:

    >>> from QuantLib import *
    >>> UnitedStates(UnitedStates.GovernmentBond).isHoliday(Date(10,November,2017))
    False
    >>> import QuantLib
    >>> QuantLib.__version__
    '1.13'
    >>>

**Comment by eddelbuettel** [comment]
Same here:

```r
R> library(RQuantLib)
R> isHoliday(calendar="UnitedStates", dates=as.Date("2017-11-10")+seq(-2,2))
[1] FALSE FALSE  TRUE  TRUE  TRUE
R> isHoliday(calendar="UnitedStates/GovernmentBond", dates=as.Date("2017-11-10")+seq(-2,2))
[1] FALSE FALSE FALSE  TRUE  TRUE
R>
```

A general holiday, but not a bond market holiday.  Using:

```r
R> RQuantLib::getQuantLibVersion()
[1] "1.13"
R> packageVersion("RQuantLib")
[1] ‘0.4.4.2’
R>
```
