### ISSUE TITLE
Rquantlib not compiling with boost 1.67

### ISSUE THREAD

**Issue by jrvarma** [eddelbuettel/rquantlib#109]
I get the following error when compiling rquantlib with boost 1.67 (I am using gcc 8.1.1 on Linux):

 `asian.cpp:115:123: error: no matching function for call to 'boost::posix_time::minutes::minutes(__gnu_cxx::__alloc_traits<std::allocator<double>, double>::value_type)'
 i]= QuantLib::Date(today.dateTime() + boost::posix_time::minutes(timeIncrements[i] * 360 * 24 * 60));`                                                                                                  

I think this is due to a change in the boost library `Boost:DateTime` that no longer accepts non-integer types. In the past, these types were implicitly cast down to integervalues. Now this requires explicit cast. 

So casting `timeIncrements[i] * 360 * 24 * 60` to `int` may solve the problem

**Comment by eddelbuettel** [comment]
That is possible.  

Can you check what QuantLib itself does there? Its newest version 1.13 has changes for Boost 1.67.  

I still have Boost 1.66 here.

**Comment by jrvarma** [comment]
As far as I can make out, QuantLib seems to be using boost `ptime` and `time_duration` instead of doing any arithmetic at all. Quite neat actually: <https://github.com/lballabio/QuantLib/blob/master/ql/time/date.cpp#L524>

`dateTime_` in that code is nothing but `boost::posix_time::ptime` <https://github.com/lballabio/QuantLib/blob/master/ql/time/date.hpp#L249>

**Comment by eddelbuettel** [comment]
Some news:  Pull request #120 fixes this, based on a simple patch I got from Debian where Boost 1.67 will soon be the default.

**Comment by eddelbuettel** [comment]
This is now in `master` so this can be closed.  Thanks for the report; I was not able to replicate it at the time as I had no (easy enough) access to Boost 1.67.

**Comment by eddelbuettel** [comment]
The package is now on CRAN.  Took a moment to get everything setup including builds on Windows where @joshuaulrich was very helpful.
