### ISSUE TITLE
Error installing R package

### ISSUE THREAD

**Issue by SimonMazzucca** [eddelbuettel/rquantlib#110]
Environment:
- Windows 7
- R 3.5.1 (32/64)

Greetings,

As per your instructions I am trying to use drat to install the package:

```
if (!require("drat")) install.packages("drat")
drat::addRepo("ghrr")
install.packages("RQuantLib", type = "binary")
```

However the 3rd line returns:
```
Warning: unable to access index for repository https://ghrr.github.io/drat/bin/windows/contrib/3.5:
  cannot open URL 'https://ghrr.github.io/drat/bin/windows/contrib/3.5/PACKAGES'
Warning message:
package ‘RQuantLib’ is not available (as a binary package for R version 3.5.1)
```

And in fact this link is a 404:
https://ghrr.github.io/drat/bin/windows/contrib/3.5

How does everybody else install the package in a windows environment?

Best,
Simon

**Comment by eddelbuettel** [comment]
Please take a look at closed issue tickets, as I recall that was just discussed.

**Comment by SimonMazzucca** [comment]
I'm sorry but I really can't find anything pertinent to my issue.

**Comment by eddelbuettel** [comment]
Well the README.md promises only that updated binaries _may_ be available.  I have no time to catch up after each R or QL release and if nobody else voliunteers then you have to install from source as we all do on other OSs.  Sorry, but limited resources.

**Comment by SimonMazzucca** [comment]
Totally understand and really appreciate.

I got it all to work a few years ago (~2015) including building QuantLib/boost itself which was not easy I remember.

Anyway if you could just share what combination of R/QLib is supposed to work on Windows I could try that.

But as far as that 404 (https://ghrr.github.io/drat/bin/windows/contrib/3.5), does that seem right to you? That might be something that needs to be addressed anyway.

Thanks again,
Simon

**Comment by eddelbuettel** [comment]
Generally speaking, I do not use Windows so you have to ask other users.  

Maybe try the `r-sig-finance` list?  I am closing this now as it is a non-issue.

**Comment by SimonMazzucca** [comment]
OK, thank you.

**Comment by eddelbuettel** [comment]
Actually closing now.  Please do ask on r-sig-finance, this needs attention but I have a lot of other things to look after too.
