### ISSUE TITLE
Package instalation error

### ISSUE THREAD

**Issue by SamoPP** [eddelbuettel/rquantlib#111]
When I try to install RQuantLib (with latest pull from RQuanLib github repo in RStudio) I get following errors:
....
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘RQuantLib’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib/libs/RQuantLib.so':
  /home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib/libs/RQuantLib.so: undefined symbol: _ZN8QuantLib4Date11monthOffsetENS_5MonthEb
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib’
* restoring previous ‘/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib’

Exited with status 1.

Just before I made this I installed QuantLib on my Ubuntu 16.04 LTS using sudo apt-get install libquantlib0v5 libquantlib0-dev . Is this causing a problem?

**Comment by eddelbuettel** [comment]
Do `sudo apt-get install r-cran-rquantlib` if you cannot compile yourself.

**Comment by eddelbuettel** [comment]
If you use RQuantLib from github (== current) you must use a more current QuantLib version, NOT the one from a two-year old Ubuntu release.  Look at my PPA on Launchpad, compile from source, or use the distro rquantlib as I wrote above. 

This is all documented.

**Comment by SamoPP** [comment]
Thanks for your answers. 

I have installed latest version of quantlib (libquantlib0v5_1.10-1xenial1 and libquantlib0-dev_1.10-1xenial1) from this PPA (https://launchpad.net/~edd/+archive/ubuntu/misc?field.series_filter=xenial). But, still, RQuantLib compiles without any complaints from compiler but the package can not be loaded:

==> R CMD INSTALL --preclean --no-multiarch --with-keep.source rquantlib

* installing to library ‘/home/username/R/x86_64-pc-linux-gnu-library/3.4’
* installing *source* package ‘RQuantLib’ ...
checking for g++... g++
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking for R... yes
checking for quantlib-config... yes
checking for Boost development files... yes
checking for minimal Boost version... yes
configure: creating ./config.status
config.status: creating src/Makevars
Completed configuration and ready to build.
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
** libs
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c affine.cpp -o affine.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c asian.cpp -o asian.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c barrier_binary.cpp -o barrier_binary.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bermudan.cpp -o bermudan.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c bonds.cpp -o bonds.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c calendars.cpp -o calendars.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c curves.cpp -o curves.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c dates.cpp -o dates.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c daycounter.cpp -o daycounter.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c discount.cpp -o discount.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c hullwhite.cpp -o hullwhite.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c implieds.cpp -o implieds.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c modules.cpp -o modules.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c sabr.cpp -o sabr.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c schedule.cpp -o schedule.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c utils.cpp -o utils.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c vanilla.cpp -o vanilla.o
g++  -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/local/include -fpermissive -I../inst/include -I. -fopenmp -DRCPP_NEW_DATE_DATETIME_VECTORS -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c zero.cpp -o zero.o
g++ -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -Wl,-z,relro -o RQuantLib.so RcppExports.o affine.o asian.o barrier_binary.o bermudan.o bonds.o calendars.o curves.o dates.o daycounter.o discount.o hullwhite.o implieds.o modules.o sabr.o schedule.o utils.o vanilla.o zero.o -L/usr/local/lib -lQuantLib -fopenmp -L/usr/lib/R/lib -lR
installing to /home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib/libs
** R
** data
** demo
** inst
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error: package or namespace load failed for ‘RQuantLib’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib/libs/RQuantLib.so':
  /home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib/libs/RQuantLib.so: undefined symbol: _ZN8QuantLib4Date11monthOffsetENS_5MonthEb
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib’
* restoring previous ‘/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib’

Exited with status 1.

**Comment by eddelbuettel** [comment]
Well:

```sh
edd@rob:~$ c++filt _ZN8QuantLib4Date11monthOffsetENS_5MonthEb
QuantLib::Date::monthOffset(QuantLib::Month, bool)
edd@rob:~$
```

and it looks like that is not in QuantLib 1.10 which you picked.  I built that once for myself when xenial was more current.  These days I _of course_ use QuantLib 1.13.

You either must use matching pair of QL and RQuantLib which currently you don't.  So if you want to use QL 1.10 use an old RQL source package too.

**Comment by SamoPP** [comment]
Hm...

I am sure I do not understand something then...

Following is my basic misunderstanding of linux, I guess.
How can I install QuantLib 1.13 (which I would love to do) from your PPA while for Xenial (I am on 16.04 LTS) your PPA has QuantLib 1.10 (https://launchpad.net/~edd/+archive/ubuntu/misc?field.series_filter=xenial)? Is there any chance I can get QuantLib 1.13 from your PPA on Ubuntu 16.04 lTS (Xenial)?

**Comment by eddelbuettel** [comment]
QL 1.13 is available there for 
- 17.10 (which I was running at the time it came out)
- 14.04 (which Travis needs)

You can use the latter as 16.04 > 14.04 so you're lucky.  

```
quantlib (1.13-1.1404.0) trusty; urgency=medium

  * PPA build for Ubuntu 14.04 ("trusty")
  * debian/control: Temporarily remove 'g++ (>= 4:5.2)' constraint

 -- Dirk Eddelbuettel <email address hidden>  Thu, 24 May 2018 21:22:51 -0500
```

**Comment by SamoPP** [comment]
Thanks.

I installed libquantlib0v5 (version 1.13-1.1404.0 from your PPA for Trusty) without any issues.

While trying to install libquantlib0-dev (version 1.13-1.1404.0 from your PPA for Trusty) I get the following error:
libquantlib0-dev:
 Depends: libboost-test1.55.0  but it is not installable
Although I have done the following before:

$ sudo apt-get install libboost-test1.58-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-test1.58-dev is already the newest version (1.58.0+dfsg-5ubuntu3.1).
libboost-test1.58-dev set to manually installed.
The following packages were automatically installed and are no longer required:
  libprotoc9v5 r-cran-boot r-cran-cluster r-cran-codetools r-cran-foreign
  r-cran-lattice r-cran-matrix r-cran-mgcv r-cran-nlme r-cran-rpart
  r-cran-spatial r-cran-survival
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

and

$sudo apt-get install libboost-test1.58.0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libboost-test1.58.0 is already the newest version (1.58.0+dfsg-5ubuntu3.1).
libboost-test1.58.0 set to manually installed.
The following packages were automatically installed and are no longer required:
  libprotoc9v5 r-cran-boot r-cran-cluster r-cran-codetools r-cran-foreign
  r-cran-lattice r-cran-matrix r-cran-mgcv r-cran-nlme r-cran-rpart
  r-cran-spatial r-cran-survival
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.

**Comment by eddelbuettel** [comment]
I am unavailable to act as your personal tutor.  If you want to the simplest recommendation: use Ubuntu 18.04.  Else build from source.

The package I support is delivered in source.  If that does not work for you, I am sorry.  What you encounter are basic packaging issues (or, rather: issue you encounter when you force yourself onto an version yet desire new packages).  

Sorry.  There is nothing more I can do for you here.  I am locking this issue.
