### ISSUE TITLE
Installing RQuantLib using BERT2

### ISSUE THREAD

**Issue by GiovanniTramontin** [eddelbuettel/rquantlib#112]
Hello,

I've been trying to install RQuantLib using the BERT2 interface for Excel, it uses R version 3.5.0. I've already tried the following solutions:

https://stackoverflow.com/questions/50026518/package-rquantlib-is-not-available-for-r-3-5-0
https://github.com/eddelbuettel/rquantlib/issues/104

But nothing seems to work. Actually, when I try to use the command line "install.packages("drat", dependencies = TRUE)" it runs forever. For the second solution I receive a permission error on the endpoint.

I'm new to R and BERT, so I don't have a clue on why it's happening. Does someone have an idea?

Thanks in advance.

**Comment by eddelbuettel** [comment]
I have no idea what BERT2 and you provided no link -- but we generally say what we can say about Windows installations in the [README.md](https://github.com/eddelbuettel/rquantlib/blob/master/README.md).  As always you may have to build from source.  I do not have the resources or time to provide Windows binaries.  @Jeroen helps greatly with a [Windows builds of the QuantLib (0.12.1) library](https://github.com/rwinlib/quantlib) so by just having RTools you may get along from source.

**Comment by GiovanniTramontin** [comment]
Thank you for your answer, I will try your suggestions : )
