### ISSUE TITLE
Bring addHoliday() function to RQuantLib

### ISSUE THREAD

**Issue by pankaj3009** [eddelbuettel/rquantlib#115]
Quantlib has addHoliday()/removeHoliday() that adds/removes a "temporary" holiday to a calendar. However, i cannot find any such feature in RQuantLib. This will be very useful for users who install RQuantLib using the binary on Windows. Also, this function will provide functionality to implement adhoc holidays, without the need for time-consuming recompilation of Quantlib.

**Comment by eddelbuettel** [comment]
That has come up in the past, and we decided against / said we cannot do it as you cannot easily _persist_ the data from one session to the next.

Easier to do something locally:
- use RQuantLib to extract holidays in favourite calendar
- store them in a local file (or db)
- add holidays to the file (or db)
- look up holidays from local file (or db).

**Comment by eddelbuettel** [comment]
Adding interfaces to `addHoliday()` and `removeHoliday()` is pretty trivial -- they only operate on the currently-set calendar and do _not_ persist.

I could add them, but not export them so you would need three colons to access them as an internal function.

**Comment by eddelbuettel** [comment]
It was quick enough so I added it:

```r
> library(RQuantLib)
> thisweek <- Sys.Date() + -2:2
> thisweek
[1] "2018-08-20" "2018-08-21" "2018-08-22" "2018-08-23" "2018-08-24"
> isHoliday("TARGET", thisweek)
[1] FALSE FALSE FALSE FALSE FALSE
> addHolidays("TARGET", Sys.Date() + -1:1)
> isHoliday("TARGET", thisweek)
[1] FALSE  TRUE  TRUE  TRUE FALSE
> removeHolidays("TARGET", Sys.Date() + -1:1)
> isHoliday("TARGET", thisweek)
[1] FALSE FALSE FALSE FALSE FALSE
> 
```

Will commit in a moment.
