### ISSUE TITLE
increase prominence of system-specific install options

### ISSUE THREAD

**Issue by ClaytonJY** [eddelbuettel/rquantlib#117]
In trying to install `RQuantLib` for the first time on a Debian-based linux distro, I tried a lot of bad things before discovering I could just `apt install r-cran-rquantlib` to avoid all the headaches of compiling from source or mismatched versions between QuantLib & RQuantLib.

Perhaps making those instructions more prominent would save someone else a bit of struggle? I think a link to the wiki in the README would have helped me out in this situation.

**Comment by eddelbuettel** [comment]
How long have you used Debian?   (I am serious here and not pulling your leg.)

**Comment by eddelbuettel** [comment]
Also, git forks affect the code in the git repository.  The Wiki is a _GitHub_ extension of the UI and orthogonal to the git repo.  If you feel like editing the wiki, edit the wiki.

That said, I think normal contributor guidelines and politesse help. I am generally in favour of 'issue ticket first, establish consensus on what to change and where' and then change, ie please don't edit the wiki just yet.

**Comment by ClaytonJY** [comment]
Long enough that I should have known to look in `r-cran-*` first, for sure, but I didn't.

I recognize the distinction between the git repo and the wiki, and am not suggesting anything change in the wiki, but rather that the wiki be more easily discoverable. That was the fourth place I looked, after the CRAN package documentation, your website page linked from there (which mentions `apt install` but not `r-cran-rquantlib`) , and the Github README, so I thought it would be helpful to make the wiki just a bit more obvious, as that's the only of those 4 places to mention the bit that ultimately solved my issues.

I did read the contributor guidelines first, and for such a small docs-only change thought it seemed reasonable to submit a potential PR just after filing this issue. I'm sorry if this was a poor choice of workflow; I was thinking submitting the issue and a (potential) fix in quick succession would be easier on you as the maintainer, but I see that may have been a misjudgement on my part.

In any case, thanks for all your work on this package; I'm only using a small part of it yet, but of the 4 packages I tried it's the only one that gave me a correct NYSE trading calendar, and for that I'm grateful.

**Comment by eddelbuettel** [comment]
Regarding discoverability:  that is indeed a hard one.  This is my oldest CRAN package, with a bit of rounding we can call it 20 years.  It has been in Debian just as long.  Just about every blog post I have written mentions the Debian package too.  So it _should_ have been clearer.  

Regarding buildability:  this is even weirder because I never work on this, really, on anything but Debian or Ubuntu (with the occassional Windows test for debugging, mainly).  @lballabio develops on Debian/Ubuntu too so ...  I would point that one back at you.  Maybe odd libraries.  Hard to tell.

Now, as for better docs.  I am all ears.  Let's chat some more here figure out what may help.

Lastly, as for calendars: Yes. We all use that. For better or worse it seems way more popular than many of the very fancy prices and other tools...  I had looked into abstracting just calendaring out but with the magic of C++ and Boost it still becomes massive too.  So may as well keep it here.

**Comment by ClaytonJY** [comment]
Holy cow, 20 years is a big milestone! Good excuse for some cake perhaps?

I unfortunately wasn't aware of the blogposts, and in my searches trying to solve my initial installation problems none of them surfaced high enough to get clicked on.

On buildability, `r-cran-rquantlib` works flawlessly on my machine, so I consider that a solved problem, at least for me. Prior to discovering that, I tried `sudo apt install libquantlib0 libquantlib-dev` + `install.packages("RQuantLib")`, but got an error about incompatible versions. I think it was that system-level `quantlib` was too _new_, but I forget; if this is of interest I could try to reproduce, but it's not holding back my usage of this package. If using `quantlib` from your `ed/misc` PPA would have been better, that might be another thing to mention somewhere.

When I posted my last comment I thought I had already made a PR; a good reminder of the downsides of making changes directly through Github w/o cloning locally. My suggestion was to add one line to the README: https://github.com/ClaytonJY/rquantlib/commit/2a1a983a226e28db63aa2b0a82fb292897a6e37b. I'll gladly submit that PR for real if you think it makes sense, but I'll hold off yet.

Thinking a bit more broadly, it would be nice to have more centralized documentation, such that whether a new user finds the package docs, or your website, or the Github README, they receive the same information. The easiest change might be to include links to the wiki in all those places, or links to wherever else you'd like to make the "canonical" source of truth; your site seems like the other clear candidate.

Another option is to have a `pkgdown` site with _everything_ in there, all the installation instructions in either the README or an article (which may or may not be a true package vignette), and point everything to that, _in lieu of_ the wiki. Might be overkill here but I'd be happy to make a PR with such a site.

As for the calendar stuff, I like what Davis has started with [calendarrr](https://github.com/DavisVaughan/calendarrr) in that it seems to be self-contained and quick-compiling, though it's still in the early stages. I don't know enough about C++ or Rcpp to speak intelligently about the different ways to do this.

**Comment by eddelbuettel** [comment]
Well, generously rounded.  First release was 2002.  So call it 16 years :)

Incompatible versions can only happen when you mix repos in a weird way.  What is your actual distro?  When I am on eg an Ubuntu machine, the QL release may be a little behind.  On Debian (testing and unstable) it should almost always be the 'upstream' version.  Now, Debian stable or Ubuntu LTS are _designed_ to not be current so you can't expect them to.   But we do have PPAs so you can mix and match and there trouble may arise. 

The problem with documentation simple is that different people have different habits and approaches.  You may go to a wiki.  Another person may google 'debian rquantlib'.  It all depends.   Even pkgdown is not a panacea: all the content it rearranges is _already there_ and will remain spread over different sections.

**Comment by eddelbuettel** [comment]
That said, your one-liner is to the README.md is compelling.  Brief, and to the point: for more, see wiki.  Now to keep the wiki current :)

[ Effectively our biggest burden was not having a windows binary.  That is taken care of.  Next might be a macOS library of QL to automate builds of RQL against.  But them macOS changes so much and often and no volunteer has stepped forward so ... ]

**Comment by ClaytonJY** [comment]
Whether you call it 16 or 20, that's still impressive!

Aha, I didn't realize distro (or stable/not) mattered so much here! I'm on Mint 18.3, based on Ubuntu 16.04 LTS, so I think that explains it, thank you. One more thing to watch out for as a linux user!

There's not anything obviously out-of-date to me on the wiki currently, but if you'd like anything updated that would be easier to tell me to do than doing it yourself, I'm happy to help.

I'll go ahead and make that PR then; happy to make any changes, of course.

Unfortunately I can't be of any help on the Mac side :(

**Comment by eddelbuettel** [comment]
Yes, both distro _and_ release matter greatly.  You were having a (more-or-less) self-inflicted problem on Mint there. But glad that is squared away.

In short, remain aware what _your version_ of _your distro_ has and how to possibly expand it. PPAs are good for Ubuntu; I cannot speak to Mint, Arch or other derivatives.

**Comment by ClaytonJY** [comment]
I don't think I've used PPA's for R stuff in particular, but in general, following the instructions for the relevant Ubuntu version tends to work well. That's certainly the case for the non-PPA official Ubuntu packages you maintain; never had any issues there.

Thanks for all the help and patience here Dirk!
