### ISSUE TITLE
Makevars.win

### ISSUE THREAD

**Issue by jeroenooms** [eddelbuettel/rquantlib#12]
The `Makevars.win` has `$(SHLIB_OPENMP_CFLAGS)` but I don't think those are used? Also the `-I` statements might be better in `CPPFLAGS`? I used:

```Make
PKG_CPPFLAGS=-I$(QUANTLIB_ROOT)/include -I../inst/include -I. -I$(BOOSTLIB)
PKG_CXXFLAGS= -fpermissive 
PKG_LIBS=-L$(QUANTLIB_ROOT)/lib${R_ARCH} -lQuantLib
```

**Comment by eddelbuettel** [comment]
1) As I recall the WRE manual recommends `$(SHLIB_OPENMP_CFLAGS)` etc in Section 1.2.1.1.  QL uses it so we may as well carry it along.

2) The `PKG_CPPFLAGS` vs `PKG_CXXFLAGS` hardly matters.  What we currently have _works_ and does not trigger emails from a certain part of the world.  

Good enough for me on both counts.  Closing this.

**Comment by eddelbuettel** [comment]
I take that back. WRE has

>   *N.B.*: Include paths are preprocessor options, not compiler options,
> and *must* be set in 'PKG_CPPFLAGS' as otherwise platform-specific paths
> (e.g. '-I/usr/local/include') will take precedence.

so I'll make the change.  It is better that way.    But OpenMP support stays.
