### ISSUE TITLE
[windows] Stability issues in recent versions

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rquantlib#122]
Thanks to quite a bit of work by @joshuaulrich building on earlier work by @jeroen we once again have Windows binaries.  That is a good thing,

The less good news is that they are not behaving.  A lof of the curve-building tools are now leading to errors or segfaults.  It would be tremendous if someone with a bit of time and energy -- and access to a Windows machine with R and the required Rtools and QuantLib -- could help debug this.  We probably need to dive into the C++ level too.  

If you can help, please get in touch here or via email.

**Comment by shrektan** [comment]
I'd like to take a try. However, QuantLib is a giant library, not sure if I can handle it... So, where to start?

**Comment by eddelbuettel** [comment]
Thanks for the note!  @joshuaulrich and I have been emailing with one other volunteer who has caught up to where we were on the weekend: reproducible failure on Windows directly from C++.  So this may well turn into a QuantLib debugging issue requires recompilations of (at least parts of) QuantLib.  Do you want to jump in?  We could take this a Google group, or Slack instance, or another repo...

**Comment by gwd999** [comment]
@eddelbuettel - I used to be a big QuantLib "fan" and I could maybe spare a bit of time on weekends … if you would just fwd me the same mail you sent shrektan I could asses if I could be of any help.  
I got a Windows10Pro with Rtools35, R3.5.1 at my hands and was playing around with the idea of setting up QuantLib on this (new) Laptop anyway - for quite some time now. This could be the right excuse to get started with it.

**Comment by eddelbuettel** [comment]
Hi @gwd999 (whoever else may be lurking):
- we are now at the (free, open, ...) mailing list https://groups.io/g/rquantlib/
- I just posted this summary https://groups.io/g/rquantlib/message/1
- It has links to two other files

Hope to see you there!

**Comment by eddelbuettel** [comment]
As a follow-up, this is now mostly taken care of.  More details over at https://groups.io/g/rquantlib 

We should have a new (and corrected) CRAN upload within days.

**Comment by eddelbuettel** [comment]
Follow-up: RQuantLib 0.4.7 is now on CRAN and it addresses these concerns thanks to great help from @shrektan, @joshuaulrich and @jeroen.  Josh deserves a particular pat on the back for tirelessly building, testing and uploading the windows library.

**Comment by eddelbuettel** [comment]
This can get closed.  Not sure why I didn't close it in December.
