### ISSUE TITLE
[macOS] library builds

### ISSUE THREAD

**Issue by eddelbuettel** [eddelbuettel/rquantlib#123]
Thanks to work by @joshuaulrich building on work by @jeroen we now have a current Windows library build of QuantLib in the [rwinlib/rquantlib](https://github.com/rwinlib/quantlib) repo.

@s-u offers a similar repo for macOS.  It would be tremendous if someone could take the instructions in the wiki and build a QuantLib library for macOS to that CRAN could provide binaries of RQuantLib.  @coatless may be able to help with toolchain issues.

If you can help, please get in touch here or via email.

**Comment by joshuaulrich** [comment]
As a point of reference, it usually takes an hour or two to build QuantLib on my Windows VM.  It's long enough that I start it, make sure it's running, then come back in a few hours.

**Comment by eddelbuettel** [comment]
FYI:
- we are now at the (free, open, ...) mailing list https://groups.io/g/rquantlib/  
- I just posted this summary https://groups.io/g/rquantlib/message/1
- It has links to two other files
- That list focuses so far on the Windows bug but may as well be used to coordinate macOS help

Hope to see you there!

**Comment by eddelbuettel** [comment]
It took four months for a certain someone to adjust his build system, but so he did ... and we now have binaries of RQuantLib for all three key architectures.  Big *big* Thank You to everybodu who helped.
