### ISSUE TITLE
RQuantLib installation issues on Ubuntu 18.04

### ISSUE THREAD

**Issue by SamoPP** [eddelbuettel/rquantlib#125]
I am trying to install latest RQuantLib on Ubuntu 18.04. But it fails. can not figure out why. Since I have latest quantlib installed from your PPA:

    username@usernameVB:~$ apt list libquantlib0v5 -a
    Listing... Done
    libquantlib0v5/bionic,now 1.13-1.1804.0 amd64 [installed]
    libquantlib0v5/bionic 1.12-1 amd64
    
    username@usernameVB:~$ apt list libquantlib0-dev -a
    Listing... Done
    libquantlib0-dev/bionic,now 1.13-1.1804.0 amd64 [installed]
    libquantlib0-dev/bionic 1.12-1 amd64

When I try to install RQuantLib the following occurs:

    * installing *source* package ‘RQuantLib’ ...
    ** package ‘RQuantLib’ successfully unpacked and MD5 sums checked
    checking whether the C++ compiler works... yes
    checking for C++ compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... no
    checking for suffix of object files... o
    checking whether we are using the GNU C++ compiler... yes
    checking whether g++ accepts -g... yes
    checking how to run the C++ preprocessor... g++ -E
    checking whether we are using the GNU C++ compiler... (cached) yes
    checking whether g++ accepts -g... (cached) yes
    checking for R... yes
    checking for quantlib-config... yes
    checking for Boost development files... yes
    checking for minimal Boost version... yes
    configure: creating ./config.status
    config.status: creating src/Makevars
    Completed configuration and ready to build.
    ** libs
    g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fdebug-prefix-map=/build/r-base-oUvOgu/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/include -fopenmp -fpermissive -I../inst/include -I. -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-oUvOgu/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c RcppExports.cpp -o RcppExports.o
    g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.4/Rcpp/include"   -g -O2 -fdebug-prefix-map=/build/r-base-oUvOgu/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/include -fopenmp -fpermissive -I../inst/include -I. -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-oUvOgu/r-base-3.5.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g -c affine.cpp -o affine.o
    affine.cpp:28:68: error: ‘BlackCalibrationHelper’ is not a member of ‘QuantLib’
                          const std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > &helpers,
                                                                        ^~~~~~~~~~~~~~~~~~~~~~
    affine.cpp:28:68: note: suggested alternative: ‘CalibrationHelper’
                          const std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > &helpers,
                                                                        ^~~~~~~~~~~~~~~~~~~~~~
                                                                        CalibrationHelper
    affine.cpp:28:68: error: ‘BlackCalibrationHelper’ is not a member of ‘QuantLib’
    affine.cpp:28:68: note: suggested alternative: ‘CalibrationHelper’
                          const std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > &helpers,
                                                                        ^~~~~~~~~~~~~~~~~~~~~~
                                                                        CalibrationHelper
    affine.cpp:28:90: error: template argument 1 is invalid
                          const std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > &helpers,
                                                                                              ^
    affine.cpp:28:92: error: template argument 1 is invalid
                          const std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > &helpers,
                                                                                                ^
    affine.cpp:28:92: error: template argument 2 is invalid
    affine.cpp: In function ‘void calibrateModel2(const boost::shared_ptr<QuantLib::ShortRateModel>&, const int&, QuantLib::Real, Rcpp::NumericVector&, Rcpp::NumericVector&, Rcpp::NumericVector&)’:
    affine.cpp:37:88: error: no matching function for call to ‘QuantLib::ShortRateModel::calibrate(const int&, QuantLib::LevenbergMarquardt&, QuantLib::EndCriteria)’
         model->calibrate(helpers, om,QuantLib:: EndCriteria(400,100,1.0e-8, 1.0e-8, 1.0e-8));
                                                                                            ^
    In file included from /usr/include/ql/pricingengines/latticeshortratemodelengine.hpp:28:0,
                     from /usr/include/ql/experimental/callablebonds/treecallablebondengine.hpp:28,
                     from /usr/include/ql/experimental/callablebonds/all.hpp:9,
                     from /usr/include/ql/experimental/all.hpp:7,
                     from /usr/include/ql/quantlib.hpp:43,
                     from ../inst/include/rquantlib_internal.h:24,
                     from affine.cpp:24:
    /usr/include/ql/models/model.hpp:99:22: note: candidate: virtual void QuantLib::CalibratedModel::calibrate(const std::vector<boost::shared_ptr<QuantLib::CalibrationHelper> >&, QuantLib::OptimizationMethod&, const QuantLib::EndCriteria&, const QuantLib::Constraint&, const std::vector<double>&, const std::vector<bool>&)
             virtual void calibrate(
                          ^~~~~~~~~
    /usr/include/ql/models/model.hpp:99:22: note:   no known conversion for argument 1 from ‘const int’ to ‘const std::vector<boost::shared_ptr<QuantLib::CalibrationHelper> >&’
    affine.cpp:41:39: error: invalid types ‘const int[QuantLib::Size {aka long unsigned int}]’ for array subscript
             QuantLib::Real npv = helpers[i]->modelValue();
                                           ^
    affine.cpp:42:49: error: invalid types ‘const int[QuantLib::Size {aka long unsigned int}]’ for array subscript
             QuantLib::Volatility implied = helpers[i]->impliedVolatility(npv, 1e-4,
                                                     ^
    affine.cpp: In function ‘Rcpp::List affineWithRebuiltCurveEngine(Rcpp::List, Rcpp::List, std::vector<QuantLib::Date>, std::vector<double>, Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)’:
    affine.cpp:157:45: error: ‘BlackCalibrationHelper’ is not a member of ‘QuantLib’
         std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > swaptions;
                                                 ^~~~~~~~~~~~~~~~~~~~~~
    affine.cpp:157:45: note: suggested alternative: ‘CalibrationHelper’
         std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > swaptions;
                                                 ^~~~~~~~~~~~~~~~~~~~~~
                                                 CalibrationHelper
    affine.cpp:157:45: error: ‘BlackCalibrationHelper’ is not a member of ‘QuantLib’
    affine.cpp:157:45: note: suggested alternative: ‘CalibrationHelper’
         std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > swaptions;
                                                 ^~~~~~~~~~~~~~~~~~~~~~
                                                 CalibrationHelper
    affine.cpp:157:67: error: template argument 1 is invalid
         std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > swaptions;
                                                                       ^
    affine.cpp:157:69: error: template argument 1 is invalid
         std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> > swaptions;
                                                                         ^
    affine.cpp:157:69: error: template argument 2 is invalid
    affine.cpp:164:19: error: request for member ‘push_back’ in ‘swaptions’, which is of non-class type ‘int’
             swaptions.push_back(boost::shared_ptr<QuantLib::BlackCalibrationHelper>(new QuantLib::SwaptionHelper(swaptionMaturities[i],
                       ^~~~~~~~~
    affine.cpp:164:57: error: ‘BlackCalibrationHelper’ is not a member of ‘QuantLib’
             swaptions.push_back(boost::shared_ptr<QuantLib::BlackCalibrationHelper>(new QuantLib::SwaptionHelper(swaptionMaturities[i],
                                                             ^~~~~~~~~~~~~~~~~~~~~~
    affine.cpp:164:57: note: suggested alternative: ‘CalibrationHelper’
             swaptions.push_back(boost::shared_ptr<QuantLib::BlackCalibrationHelper>(new QuantLib::SwaptionHelper(swaptionMaturities[i],
                                                             ^~~~~~~~~~~~~~~~~~~~~~
                                                             CalibrationHelper
    affine.cpp:164:57: error: ‘BlackCalibrationHelper’ is not a member of ‘QuantLib’
    affine.cpp:164:57: note: suggested alternative: ‘CalibrationHelper’
             swaptions.push_back(boost::shared_ptr<QuantLib::BlackCalibrationHelper>(new QuantLib::SwaptionHelper(swaptionMaturities[i],
                                                             ^~~~~~~~~~~~~~~~~~~~~~
                                                             CalibrationHelper
    affine.cpp:164:79: error: template argument 1 is invalid
             swaptions.push_back(boost::shared_ptr<QuantLib::BlackCalibrationHelper>(new QuantLib::SwaptionHelper(swaptionMaturities[i],
                                                                                   ^
    affine.cpp:172:19: error: request for member ‘back’ in ‘swaptions’, which is of non-class type ‘int’
             swaptions.back()->addTimesTo(times);
                       ^~~~
    affine.cpp:199:34: error: request for member ‘size’ in ‘swaptions’, which is of non-class type ‘int’
             for(i = 0; i < swaptions.size(); i++)
                                      ^~~~
    affine.cpp:200:24: error: invalid types ‘int[QuantLib::Size {aka long unsigned int}]’ for array subscript
                 swaptions[i]->setPricingEngine(boost::shared_ptr<QuantLib::PricingEngine>(new QuantLib::G2SwaptionEngine(modelG2, 6.0, 16)));
                            ^
    affine.cpp:217:31: error: request for member ‘size’ in ‘swaptions’, which is of non-class type ‘int’
             for (i=0; i<swaptions.size(); i++)
                                   ^~~~
    affine.cpp:218:24: error: invalid types ‘int[QuantLib::Size {aka long unsigned int}]’ for array subscript
                 swaptions[i]->setPricingEngine(boost::shared_ptr<QuantLib::PricingEngine>(new QuantLib::JamshidianSwaptionEngine(modelHW)));
                            ^
    affine.cpp:232:31: error: request for member ‘size’ in ‘swaptions’, which is of non-class type ‘int’
             for (i=0; i<swaptions.size(); i++)
                                   ^~~~
    affine.cpp:233:24: error: invalid types ‘int[QuantLib::Size {aka long unsigned int}]’ for array subscript
                 swaptions[i]->setPricingEngine(boost::shared_ptr<QuantLib::PricingEngine>(new QuantLib::TreeSwaptionEngine(modelHW2,grid)));
                            ^
    affine.cpp:249:31: error: request for member ‘size’ in ‘swaptions’, which is of non-class type ‘int’
             for (i=0; i<swaptions.size(); i++)
                                   ^~~~
    affine.cpp:250:24: error: invalid types ‘int[QuantLib::Size {aka long unsigned int}]’ for array subscript
                 swaptions[i]->setPricingEngine(boost::shared_ptr<QuantLib::PricingEngine>(new QuantLib::TreeSwaptionEngine(modelBK,grid)));
                            ^
    /usr/lib/R/etc/Makeconf:168: recipe for target 'affine.o' failed
    make: *** [affine.o] Error 1
    ERROR: compilation failed for package ‘RQuantLib’
    * removing ‘/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib’
    * restoring previous ‘/home/username/R/x86_64-pc-linux-gnu-library/3.4/RQuantLib’
    Warning in install.packages :
      installation of package ‘RQuantLib’ had non-zero exit status

I would appreciate a hint which dependencies I have messed up. Again... :) Thanks.

**Comment by eddelbuettel** [comment]
You don't have the latest from my PPA -- you need 1.14:

```sh
edd@rob:~$ COLUMNS=90 dpkg -l | grep libquantlib 
ii  libquantlib0-dev 1.14-1.1804.0 amd64         Quantitative Finance Library -- develo
ii  libquantlib0v5   1.14-1.1804.0 amd64         Quantitative Finance Library -- librar
edd@rob:~$ 
```

and 

```sh
edd@rob:~$ grep ^deb /etc/apt/sources.list.d/edd-ubuntu-misc-artful.list
deb http://ppa.launchpad.net/edd/misc/ubuntu bionic main 
edd@rob:~$ 
```

You should also upgrade to R 3.5.0 via the CRAN repo but that is another issue...
