### ISSUE TITLE
Loading and compilation failure upon update to QuantLib 1.15

### ISSUE THREAD

**Issue by gp2x** [eddelbuettel/rquantlib#129]
I recently updated to QuantLib 1.15, which in Arch Linux is not provided as a precompiled package but only a recipe: [https://aur.archlinux.org/packages/quantlib/](https://aur.archlinux.org/packages/quantlib/)

After doing so, the command `library(RQuantLib)` fails with error:

`Error: package or namespace load failed for ‘RQuantLib’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '~/R/x86_64-pc-linux-gnu-library/3.5/RQuantLib/libs/RQuantLib.so':
  ~/R/x86_64-pc-linux-gnu-library/3.5/RQuantLib/libs/RQuantLib.so: undefined symbol: _ZNK8QuantLib9CPICoupon15checkPricerImplERKN5boost10shared_ptrINS_21InflationCouponPricerEEE`

Attempting to re-install QuantLib with `install.packages("RQuantLib")` also fails; the first of many error lines is:
`affine.cpp: In function ‘void calibrateModel2(const boost::shared_ptr<QuantLib::ShortRateModel>&, const std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> >&, QuantLib::Real, Rcpp::NumericVector&, Rcpp::NumericVector&, Rcpp::NumericVector&)’:
affine.cpp:37:88: error: no matching function for call to ‘QuantLib::ShortRateModel::calibrate(const std::vector<boost::shared_ptr<QuantLib::BlackCalibrationHelper> >&, QuantLib::LevenbergMarquardt&, QuantLib::EndCriteria)’
     model->calibrate(helpers, om,QuantLib:: EndCriteria(400,100,1.0e-8, 1.0e-8, 1.0e-8));`

My sessionInfo() output is:

```
R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Antergos Linux

Matrix products: default
BLAS: /usr/lib/libblas.so.3.8.0
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] zoo_1.8-4       compiler_3.5.2  tools_3.5.2     Rcpp_1.0.0     
[5] grid_3.5.2      lattice_0.20-38 tcltk_3.5.2
```

The Arch version of QuantLib I have is 1.15-1 and of the boost libraries is 1.69.0-1. I did not have any issues compiling/installing QuantLib 1.15 on my system using the AUR. Let me know if there's any more info you need.

**Comment by eddelbuettel** [comment]
I fear you need to sort this out with the Arch folks.  The package works in Debian (I am maintainer) and Ubuntu (in the distro; also via a PPA I maintain).   I know too little about Arch to help, and the _source_ has no issue so I suggest we may want to close this here.

**Comment by gp2x** [comment]
Roger, I'll pursue that route and see what happens. If any useful info is uncovered I'll report back. Thanks for your time and your quick response.

**Comment by eddelbuettel** [comment]
BTW try `c++filt` on the symbol, and check QuantLib.  Most likely Arch is just one release behind or something like that:

```sh
edd@rob:~$ c++filt _ZNK8QuantLib9CPICoupon15checkPricerImplERKN5boost10shared_ptrINS_21InflationCouponPricerEEE
QuantLib::CPICoupon::checkPricerImpl(boost::shared_ptr<QuantLib::InflationCouponPricer> const&) const
edd@rob:~$
```

If you are comfortable compiling from source you follow the route of my QuantLib packages in the PPA.

**Comment by gp2x** [comment]
Thanks for the tip. I get the exact same results on my end running c++filt.

I'll try compiling from source when I have time.

**Comment by eddelbuettel** [comment]
So what does `dpkg -l | grep quantlib` give for Arch?  _Why_ would the supplied one be bad?

**Comment by gp2x** [comment]
The Arch equivalent to `dpkg -l` is `pacman -Q`; that command returns
`quantlib 1.15-1`

As to why the supplied one is bad, if I look at the changes to the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/diff/?h=quantlib) it appears the compile option `--enable-std-function` was added.

**Comment by eddelbuettel** [comment]
Good detective work. So the Arch version uses the 'new' framework of C++11/14 instead if Boost.

Conceivably it may also be a bug in RQuantLib to not respond to that.   You could dig there too.  I may not have time to build another version of QuantLib to test it.

Or, you could backtrack and build QuantLib locally without that flag and see if that works better for you.

**Comment by gp2x** [comment]
More results:

1. Using the previous PKGBUILD, if I compile and install quantlib 1.14 I get no issues loading or running RQuantLib.

2. If I manually compile and install quantlib 1.15 using the current PKGBUILD I get the errors I've been seeing.

3. If I manually compile and install quantlib 1.15 using the previous build options (i.e. changing `--enable-std-classes` back to `--enable-std-class` and deleting `--enable-std-function`) everything works again - I can install, load, and run RQuantLib just fine.

As I'm not an expert I don't know what these compile options actually do, but I'll circle back to the Arch package maintainers and let them know what I've found.

**Comment by gp2x** [comment]
User "thrasibule" responded on the AUR page for quantlib saying that I need this patch:

[https://github.com/thrasibule/rquantlib/commit/c458c09c94f38c5335197741320635e17c03d7ca](https://github.com/thrasibule/rquantlib/commit/c458c09c94f38c5335197741320635e17c03d7ca)

Would there be issues if this were integrated into the main codebase?

**Comment by eddelbuettel** [comment]
Yes there would ... as long as people like myself use the other flag.

What we need is a means to determine how QL was configure and the do either or in RQL. I'll talk to QL upstream.

**Comment by eddelbuettel** [comment]
Actually, it may already be there.   Can you tell me what these lines look like for you on Arch in the file `config.hpp` in QL's main include directory?  

I have what follows below, yours is probably different and RQuantLib should probably adjust.  Should be easy enough -- and with your help we can probably test it.

```c++
/* Define this if you want to use std::function and std::bind. */
/* #undef QL_USE_STD_FUNCTION */

/* Define this if you want to use standard smart pointers. */
/* #undef QL_USE_STD_SHARED_PTR */

/* Define this if you want to replace std::auto_ptr with std::unique_ptr. */
/* #undef QL_USE_STD_UNIQUE_PTR */

/* Define to 1 if you have the ANSI C header files. */
#define QL_STDC_HEADERS 1
```

**Comment by gp2x** [comment]
Hm, it looks like those lines are identical on my end.

On Arch the way I build the package manually is to download the [https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=quantlib](PKGBUILD) into a new directory and then, from that directory, execute `makepkg`. The PKGBUILD is just a set of build instructions; looking into it the way the current recipe builds the package is simply:

```
  ./autogen.sh
  ./configure --prefix=/usr --enable-intraday --enable-openmp --disable-static --enable-std-classes --enable-std-function
  make
```
...and for source it's using the unmodified QuantLib source it downloads from:
`https://bintray.com/quantlib/releases/download_file?file_path=QuantLib-1.15.tar.gz`

**Comment by gp2x** [comment]
Apologies, did not mean to re-open the issue.

**Comment by eddelbuettel** [comment]
The point is that it configures differently from what I do for Debian/Ubuntu and that should be detectable.  Hm.

**Comment by eddelbuettel** [comment]
Can you please look again?  I tried run `configure` here with the two added flags `--enable-std-classes --enable-std-function` and I now see the difference I expected:

```diff
 /* Define this if you want to use std::function and std::bind. */
-/* #undef QL_USE_STD_FUNCTION */
+#define QL_USE_STD_FUNCTION 1

 /* Define this if you want to use standard smart pointers. */
-/* #undef QL_USE_STD_SHARED_PTR */
+#define QL_USE_STD_SHARED_PTR 1

 /* Define this if you want to replace std::auto_ptr with std::unique_ptr. */
-/* #undef QL_USE_STD_UNIQUE_PTR */
+#define QL_USE_STD_UNIQUE_PTR 1
```

Here red is what is still default on Debian and Ubuntu as I _not_ set those flags. Green is what I would get if I set -- and what I suspect you have.  Look close as to whether you have `#undef` or `#define` for those.

**Comment by thrasibule** [comment]
You don't need to know how QuantLib was configured to fix it on the RQuantLib side. You can just use QuantLib::ext::shared_ptr instead of boost::shared_ptr unconditionally: ext::shared_ptr will be a boost::shared_ptr or an std::shared_ptr depending on how Quantlib was compiled.

**Comment by eddelbuettel** [comment]
Dang, you're right! That was the gist of Luigi's long blog post on this.  I guess I got myself into a little forest / trees thinking here overcomplicating things.   With that I should be able to wrap this up (and owe CRAN an updated version for another (minor) issue anyway).

**Comment by gp2x** [comment]
This may no longer be relevant, but when I replied regarding details of the specific lines in `config.hpp` that you asked about, I was referring to the version I rebuilt with the previous compile options. If I compile including the latest options (including `--enable-std-classes` and `--enable-std-function`) then those lines in `config.hpp` look like:

```
/* Define this if you want to use std::function and std::bind. */
#define QL_USE_STD_FUNCTION 1

/* Define this if you want to use standard smart pointers. */
#define QL_USE_STD_SHARED_PTR 1

/* Define this if you want to replace std::auto_ptr with std::unique_ptr. */
#define QL_USE_STD_UNIQUE_PTR 1

/* Define to 1 if you have the ANSI C header files. */
#define QL_STDC_HEADERS 1
```

...as you expected.

**Comment by eddelbuettel** [comment]
Gotcha.  We're all square.  On the commute in I converted the first function, so we should have something for you "soon" to test under these new flags.

**Comment by eddelbuettel** [comment]
@gp2x I now have this taken care of -- thanks to @thrasibule waving the cluebat in my direction.

At this minute it a branch of master but I am preparing a PR and may soon merge this into master.  If you want to test it that would be appreciated.  It should (as pointed out by @thrasibule) just work but the tests running here and at Travis only see the one possible configuration for QuantLib.

**Comment by gp2x** [comment]
Thanks very much; I should have time next week.

**Comment by eddelbuettel** [comment]
No worries, I figured it was ready and I had time now so I uploaded it -- now on CRAN as 0.4.8.

**Comment by gp2x** [comment]
This morning I:

* Un-installed QuantLib
* Updated all packages on my Arch install
* Re-built and re-installed the latest QuantLib from the [AUR](https://aur.archlinux.org/packages/quantlib/)
* started R and did `update.packates()` to update RQuantLib to 0.4.8


Installation of RQuantLib 0.4.8 fails with the following error:
```
affine.cpp: In function ‘Rcpp::List affineWithRebuiltCurveEngine(Rcpp::List, Rcpp::List, std::vector<QuantLib::Date>, std::vector<double>, Rcpp::NumericVector, Rcpp::NumericVector, Rcpp::NumericVector)’:
affine.cpp:92:68: error: no matching function for call to ‘QuantLib::Handle<QuantLib::YieldTermStructure>::Handle(boost::shared_ptr<QuantLib::YieldTermStructure>)’
         rhTermStructure(rebuildCurveFromZeroRates(dateVec, zeroVec));
                                                                    ^
In file included from /usr/include/ql/quantlib.hpp:22,
                 from ../inst/include/rquantlib_internal.h:23,
                 from affine.cpp:23:
/usr/include/ql/handle.hpp:75:18: note: candidate: ‘QuantLib::Handle<T>::Handle(const std::shared_ptr<_Tp>&, bool) [with T = QuantLib::YieldTermStructure]’
         explicit Handle(const ext::shared_ptr<T>& p = ext::shared_ptr<T>(),
                  ^~~~~~
/usr/include/ql/handle.hpp:75:18: note:   no known conversion for argument 1 from ‘boost::shared_ptr<QuantLib::YieldTermStructure>’ to ‘const std::shared_ptr<QuantLib::YieldTermStructure>&’
/usr/include/ql/handle.hpp:41:11: note: candidate: ‘QuantLib::Handle<QuantLib::YieldTermStructure>::Handle(const QuantLib::Handle<QuantLib::YieldTermStructure>&)’
     class Handle {
           ^~~~~~
/usr/include/ql/handle.hpp:41:11: note:   no known conversion for argument 1 from ‘boost::shared_ptr<QuantLib::YieldTermStructure>’ to ‘const QuantLib::Handle<QuantLib::YieldTermStructure>&’
/usr/include/ql/handle.hpp:41:11: note: candidate: ‘QuantLib::Handle<QuantLib::YieldTermStructure>::Handle(QuantLib::Handle<QuantLib::YieldTermStructure>&&)’
/usr/include/ql/handle.hpp:41:11: note:   no known conversion for argument 1 from ‘boost::shared_ptr<QuantLib::YieldTermStructure>’ to ‘QuantLib::Handle<QuantLib::YieldTermStructure>&&’
```

Let me know if you need any more details.

**Comment by eddelbuettel** [comment]
That is in a file from QL proper -- `handle.cpp`.  So no my department :)

**Comment by thrasibule** [comment]
You can't have rebuildCurveFromZeroRates return a boost::shared_ptr. Everything needs to switch to ext::shared-ptr.

**Comment by gp2x** [comment]
Just to clarify, is an interim release addressing this boost::shared_ptr vs. ext::shared-ptr issue planned? Or should I plan on staying with QuantLib 1.14 / RQuantLib 0.4.7 until a new release needs to happen for other reasons? I'm fine either way.

**Comment by eddelbuettel** [comment]
> Everything needs to switch to ext::shared-ptr.

And that is what we did in 0.4.8.  See [the ChangeLog](https://cloud.r-project.org/web/packages/RQuantLib/ChangeLog)  To be honest I am not sure _what_ your issue is. I work on Linux and hence install from source and directly against (current) QL too.  "Works for me."

Maybe you can clarify with something reprorducible.    The package also builds at CRAN (modulo one compiler error on macOS, possibly lack of RAM).

**Comment by thrasibule** [comment]
@eddelbuettel No you didn't: see https://github.com/eddelbuettel/rquantlib/blob/4a936913c3eb0fee831208ca36ef23dc9c2e6885/inst/include/rquantlib_internal.h#L178 for this particular case. rebuildCurveFromZeroRates is called everywhere, and you can't pass it to QuantLib constructors which expect a std::shared_ptr. I suggest to do a sed "/boost::shared_ptr/QuantLib::ext::shared_ptr" on the whole code base.
To reproduce the issue you need to build quantlib with --enable-std-classes.

**Comment by eddelbuettel** [comment]
Well turns changes had been limited to `src/` and omitted `inst/include`. Easy enough to fix.  I'll get to it.

**Comment by thrasibule** [comment]
I've added a comment to the PR. Just one small fix and it should be done.

**Comment by eddelbuettel** [comment]
Saw it, much apreciated,  Will push once the current Travis run is done.

**Comment by eddelbuettel** [comment]
Release 0.4.9 is now on CRAN (after a wait of a few days for a manual approval as the build fails/failed on macOS for what looks like an unrelated issue).

**Comment by gp2x** [comment]
Greetings Gentlemen. I just now:

* Updated all packages on my Arch install.
* Re-built and re-installed the latest QuantLib from the [AUR](https://aur.archlinux.org/packages/quantlib/)
* started R and did `update.packages()` to update RQuantLib to 0.4.9
* tested loading RQuantLib in an R session and executing misc. QuantLib functions.

Everything looks good! Thanks and Danke Schön for your time and attention on this.

**Comment by eddelbuettel** [comment]
Thanks for patiently keeping on it.  Because we compile with the default settings over in Debian / Ubuntu I was unaware of the issues.  That "should" never have been an issue but in the haste of getting 0.4.8 out it reremained incomplete.  Glad to know it is better now.
