### ISSUE TITLE
Compilation error on Ubuntu 18.04 (same as #137)

### ISSUE THREAD

**Issue by SamoPP** [eddelbuettel/rquantlib#138]
Trying to install RQuantLib on host machine (I used RQuantLib on virtualbox only up until this moment). And I get the same error as reported in closed #137 .

`username@username-G501JW:~$ R

R version 3.6.1 (2019-07-05) -- "Action of the Toes"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> install.packages("RQuantLib")
Installing package into ‘/home/username/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RQuantLib_0.4.10.tar.gz'
Content type 'application/x-gzip' length 188289 bytes (183 KB)
==================================================
downloaded 183 KB

* installing *source* package ‘RQuantLib’ ...
** package ‘RQuantLib’ successfully unpacked and MD5 sums checked
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -std=gnu++11 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -std=gnu++11 accepts -g... (cached) yes
checking for R... yes
checking for quantlib-config... yes
checking for Boost development files... yes
checking for minimal Boost version... yes
configure: creating ./config.status
config.status: creating src/Makevars
Completed configuration and ready to build.
** libs
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG  -I"/home/username/R/x86_64-pc-linux-gnu-library/3.6/Rcpp/include"  -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -I/usr/include -fopenmp -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -g -O2 -fdebug-prefix-map=/build/r-base-uuRxut/r-base-3.6.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
In file included from ../inst/include/RQuantLib.h:22:0,
                 from RcppExports.cpp:4:
../inst/include/rquantlib_internal.h:26:10: fatal error: ql/shared_ptr.hpp: No such file or directory
 #include <ql/shared_ptr.hpp>
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
/usr/lib/R/etc/Makeconf:176: recipe for target 'RcppExports.o' failed
make: *** [RcppExports.o] Error 1
ERROR: compilation failed for package ‘RQuantLib’
* removing ‘/home/username/R/x86_64-pc-linux-gnu-library/3.6/RQuantLib’

The downloaded source packages are in
	‘/tmp/RtmpiMnfxM/downloaded_packages’
Warning message:
In install.packages("RQuantLib") :
  installation of package ‘RQuantLib’ had non-zero exit status
> 
`
I have all the libraries installed from your repo:
![quantlib](https://user-images.githubusercontent.com/4817398/64116185-9fe9d600-cd5f-11e9-8f7e-ae2282a00347.png)

While looking into folder /usr/include/ql I see the files reported are indeed missing... (I re-installed, removed, installed again etc. many times.)

Also, instructions from here https://github.com/eddelbuettel/rquantlib/wiki/RQuantLib for Debina and Ubuntu do not work do to dependency issues (dependency on zoo and then on r-api-3.4 or something if I correctly remember).

**Comment by eddelbuettel** [comment]
Wrong repo.  Use https://launchpad.net/~edd/+archive/ubuntu/r-3.5 

"We all"l switched to '3.5' post 3.5 release as widely discussed.

**Comment by eddelbuettel** [comment]
Also reopening a closed bug with the same message on purpose is ... a little rude, no?  If you know (or think) you have the same issue, should you not append it to the existing ticket?   What do we gain from duplicating this?

**Comment by SamoPP** [comment]
I was not aware that there was a change post 3.5 release. Unfortunately this is the first time I see this. I got my instructions first from here https://github.com/eddelbuettel/rquantlib/wiki/RQuantLib and since it did not work I remembered how I for the first time (by accident) stumbled on your repo by following instructions here https://www.quantlib.org/install/linux.shtml where they briefly mention your repo "to get a recent one, use the "unstable" (a.k.a. "Sid") distribution on Debian or Dirk Eddelbuettel's PPA on Ubuntu." .

I had no idea it is considered rude to open an issue (I read through the closed ones) and found one which is describing the same problem as I posted in a new issue (since I thought this is the correct way) and now see that one can comment on closed issues - I thought comments on closed issues are disabled).

I am extremely grateful for the software you created and you are maintaining and for all the support you provided me personally and to the community.

If I may, I would suggest you mention your repo https://launchpad.net/~edd/+archive/ubuntu/r-3.5 in all the Readme.md files that rely on compiled libraries.

**Comment by eddelbuettel** [comment]
That's ok -- if you are unable / unaware to follow best practices, I would recommend to just use the distribution.  There is a reason it has pre-made binaries, so maybe just rely on `apt-get install r-cran-rquantlib` -- see the package page https://packages.ubuntu.com/search?keywords=r-cran-rquantlib if you use Ubuntu. 

If you need something newer, consult with a specialist.  This is not a small package, and not a trivial build.  It helps to be a little familiar with how the distro works and where and how to extend it.   All this can be learned, but I recommend against just following random blog and selecting random repos.  As you learned, this can be stale.  Nobody has time to update all documentation at all times.  If you see discrepancies, maybe you can compile a list for someone to follow up on.

Thanks for your enthusiasm about RQuantLib.

**Comment by SamoPP** [comment]
Thanks. I tried to use the documented path here https://github.com/eddelbuettel/rquantlib/wiki/RQuantLib which says use "Debian and Ubuntu
Simply sudo apt-get install r-cran-rquantlib installs the RQuantLib package for R. If you want the headers and examples of QuantLib as well, please execute sudo apt-get install r-cran-rquantlib quantlib-examples libquantlib0-dev." . And I got errors below so I tried using install.packages and this lead to opening this issue....

username@username-G501JW:~$ sudo apt-get install r-cran-rquantlib
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-rquantlib : Depends: r-cran-rcpp (>= 0.11.0) but it is not going to be installed
                    Depends: r-cran-zoo but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
username@username-G501JW:~$ sudo apt-get install r-cran-zoo
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 r-cran-zoo : Depends: r-api-3.4
E: Unable to correct problems, you have held broken packages.
username@username-G501JW:~$ sudo apt-get install r-api-3.4
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package r-api-3.4 is a virtual package provided by:
  r-base-core 3.4.4-1ubuntu1 [Not candidate version]

E: Package 'r-api-3.4' has no installation candidate

**Comment by eddelbuettel** [comment]
If you remove all external repos it will work.

If you connect external repos _consistently_ (ie all post 3.5) it will work. I use the binaries myself on two machines using the repo I linked to.

**Comment by SamoPP** [comment]
I only have this repo https://launchpad.net/~edd/+archive/ubuntu/r-3.5 . And as shown above, it does not work for me. Or, maybe, I do not know and understand a couple of things. It wouldn't be the firet time. Anyhow, I managed to install RQuantLib now using install.packages after installing quantlib from https://launchpad.net/~edd/+archive/ubuntu/r-3.5 .

**Comment by eddelbuettel** [comment]
You probably want the above PPA by me in conjunction with the marutter PPAs; see his README at the CRAN page https://cloud.r-project.org/bin/linux/ubuntu/README.html
