### ISSUE TITLE
brew install quantlib --with-intraday . no longer works

### ISSUE THREAD

**Issue by nassuphis** [eddelbuettel/rquantlib#141]
This no longer works:

``brew install quantlib --with-intraday``

https://github.com/Homebrew/brew/issues/5732#issuecomment-463568419

"Homebrew/homebrew-core formulae no longer have install options"

the wiki describing how to install RQuantLib from source on OSX is now incorrect

**Comment by eddelbuettel** [comment]
Thanks for the note. I am actually not a macOS user so I would have to rely on another volunteer to check and test this.

**Comment by YourEconProf** [comment]
From looking at the[ Homebrew Formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/quantlib.rb), it appears that the option --enable-intraday is selected by default during the Homebrew install.

**Comment by eddelbuettel** [comment]
That's good.  We can probably close this now, no?

**Comment by YourEconProf** [comment]
Not sure, as the error still appears regardless of this change.

**Comment by eddelbuettel** [comment]
Well someone needs to talk to whoever maintains _the brew build for this_ which isn't me.  As I can't help here, I will close this.

It will work if you build (with the correct / desired options) from source.
