### ISSUE TITLE
cannot install RQuantLib on Fedora

### ISSUE THREAD

**Issue by waynelapierre** [eddelbuettel/rquantlib#147]
When installing the package RQuantLib, I got the error message:
```

 checking for quantlib-config... no
configure: error: Please install QuantLib before trying to build RQuantLib.

```
However, I have already installed boost and QuantLib:

```
Package boost-devel-1.69.0-9.fc31.x86_64 is already installed.
Package QuantLib-1.16-1.fc31.x86_64 is already installed.

```

**Comment by eddelbuettel** [comment]
Maybe Fedora does what everybody else and split a package for _Foo_ into the
- run-time package foo or for a library libfoo
- development package libfoo-dev

I can only tell you that the test I encoded in the `configure` script failed to find QuantLib (specifically to find `quantlib-config`).  

If you _really_ know that you have the headers and the linkable library you _could_ locally override by writing the values by hand into `src/Makevars` and by deleting `configure`.    

Let me know if either approach works.

There does not seem to be a genuine bug in RQuantLib though.

**Comment by eddelbuettel** [comment]
Oh, and for completeness, here we see

```sh
edd@rob:~$ quantlib-config --libs
-L/usr/lib -lQuantLib -fopenmp
edd@rob:~$ quantlib-config --cflags
-I/usr/include -fopenmp
edd@rob:~$ 
```

**Comment by waynelapierre** [comment]
I just solved this issue by installing QuantLib-devel. 
For many other packages, when there is an error during installation, the error message will tell me what to install. Could you add this error message (for Fedora OS) to your package, like "please install: boost, boost-devel, QuantLib, QuantLib-devel"? Thanks.

**Comment by eddelbuettel** [comment]
If you provide a list of what these are called on other OSs, sure.  

Otherwise it is somewhat common knowledge among people building from source.  I can expand the line to

```
configure: error: Please install QuantLib (or an applicable QuantLib development package) before trying to build RQuantLib.
```

but it is not clear that that is better.
