### ISSUE TITLE
Problems with require(RQuantLib)

### ISSUE THREAD

**Issue by jmagomez** [eddelbuettel/rquantlib#151]
Dear Fellows, 

I am successful in installing RQuantLib, but when I require RQuantLib returns me this error:

> library(RQuantLib)
Error: package or namespace load failed for ‘RQuantLib’ in inDL(x, as.logical(local), as.logical(now), ...):
 unable to load shared object 'C:/Users/User/Documents/R/win-library/4.0/RQuantLib/libs/x64/RQuantLib.dll':
  LoadLibrary failure:  Não foi possível encontrar o procedimento especificado.
In addition: Warning message:
package ‘RQuantLib’ was built under R version 4.0.2 

I do not know what I have to do, because all others packages when I require, I do not receive an error message. I am working with R4.0.0 and RTools 4.0.

Thanks for your support.

Best Regards.

**Comment by eddelbuettel** [comment]
That suggests you were _not_ successful in install RQuantLib as it doesn't load.  We would know how you built it.

There is a binary for Windows at CRAN ....

**Comment by jmagomez** [comment]
Thanks,

I have downloaded the file from:

https://cran.r-project.org/bin/windows/contrib/4.0/

Replaced the RQuantLib installed and updated all the packages from R. So I
have made the require, but I have received the same error.

After this, I removed RQuantLib and I tried to install RQuantLib from CRAN:

> install.packages("RQuantLib")
Installing package into ‘C:/Users/User/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
trying URL '
https://cran.rstudio.com/bin/windows/contrib/4.0/RQuantLib_0.4.12.zip'
Content type 'application/zip' length 9466047 bytes (9.0 MB)
downloaded 9.0 MB

package ‘RQuantLib’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
C:\Users\User\AppData\Local\Temp\RtmpiEqLUD\downloaded_packages


Finally, I received this  message when I required RQuantLib:

> library(RQuantLib)
Error: package or namespace load failed for ‘RQuantLib’ in inDL(x,
as.logical(local), as.logical(now), ...):
 unable to load shared object
'C:/Users/User/Documents/R/win-library/4.0/RQuantLib/libs/x64/RQuantLib.dll':
  LoadLibrary failure:  Não foi possível encontrar o procedimento
especificado.
In addition: Warning message:
package ‘RQuantLib’ was built under R version 4.0.2
>

And the RQuantLib file is available at the path mentioned above:
C:\Users\User\Documents\R\win-library\4.0\RQuantLib

Sorry, but could you help me again.

Thanks a lot. Best Regards.

Em sex., 26 de jun. de 2020 às 12:21, Dirk Eddelbuettel <
notifications@github.com> escreveu:

**Comment by eddelbuettel** [comment]
Please subscribe to the rquantlib mailing list at groups.io:   https://groups.io/g/rquantlib

There are some Windows users on the list.  I do not know what you did wrong yet your description is not entirely -- but there is no bug in RQuantLib.  It builds on Windows from source at CRAN and is installable.  So I am closing this as it is not really an "issue".

**Comment by jmagomez** [comment]
Ok. Thanks and one last attempt, I tried again and received that message:

[image: image.png]

Translating this sentence means: It could not find entry point for
procedure EXTPTR_PTR in dynamic link
library C:/Users/User/Documents/R/win-library/4.0/RQuantLib/libs/x64/RQuantLib.dll

Best Regards.



Em sex., 26 de jun. de 2020 às 14:03, Dirk Eddelbuettel <
notifications@github.com> escreveu:
