### ISSUE TITLE
Wrong count of business days for Brazil

### ISSUE THREAD

**Issue by GitHunter0** [eddelbuettel/rquantlib#152]
This function is returning 7 days when it should return 4, it is even counting the weekend days.
```
RQuantLib::businessDaysBetween(
  calendar="Brazil",
  from=as.Date("2020-09-06"), to=as.Date("2020-09-12"),
  includeFirst = TRUE, includeLast = TRUE)
```
 I appreciate if you can assess the issue.

**Comment by eddelbuettel** [comment]
What version of RQuantLib are you running?  Against which version of QuantLib?  

I get a different value here -- RQuantLib 0.4.12 using QuantLib 1.19"

```r
R> library(RQuantLib)
R> businessDaysBetween(calendar="Brazil",  from=as.Date("2020-09-06"), to=as.Date("2020-09-12"), 
                                           includeFirst = TRUE, includeLast = TRUE)
[1] 4
R> 
```

**Comment by GitHunter0** [comment]
I'm running the same version. I executed the code several times to make sure the result was indeed 7. 
However, something might have caused conflict on RQuantLib package because, now that I restarted my R session, the result is correct, 4. 
I'm glad it is working as expected now, it is a very useful package. 
Thank you very much
