### ISSUE TITLE
Add more quantlib calendars 

### ISSUE THREAD

**Issue by wilsonfreitas** [eddelbuettel/rquantlib#155]
Hi,

Quantlib has more calendar than those available in RQuantlib.

<https://github.com/lballabio/QuantLib/tree/master/ql/time/calendars>

For example, the French calendar

```
RQuantLib::businessDaysBetween(calendar="France",
                               from=as.Date("2020-01-01"),
                               to=as.Date("2020-12-31"),
                               includeFirst = TRUE, includeLast = FALSE)
```

raises this error

```
Error in RQuantLib::businessDaysBetween(calendar = "France", from = as.Date("2020-01-01"),  : 
  Calendar France not recognised 
```

These calendars might be added to rquantlib.

**Comment by eddelbuettel** [comment]
Yes, I would be open to careful pull request, maybe one calendar / country at a time.

**Comment by eddelbuettel** [comment]
(As an aside there is also the somewhat-dormant-and-behind [Quantuccia](https://github.com/pcaspers/Quantuccia) which I wrapped in [RcppQuantuccia](https://github.com/eddelbuettel/rcppquantuccia). While smaller, it is also header-only and hence more portable.

Maybe a few of us should look into reviving it / catching it up to QuantLib ...

**Comment by wei-wu-nyc** [comment]
I would also like to request adding "UnitedStates/FederalReserve" calendar. Thanks.

**Comment by eddelbuettel** [comment]
I was unaware that existed, ditto for "LiborImpact". Should be simple to add.  Did you try?

**Comment by eddelbuettel** [comment]
It's a two-liner. I'll push that to a new branch in a minute.

```r
> library(RQuantLib)
> hl <- holidayList("UnitedStates/FederalReserve", from=as.Date("2021-01-01"), to=as.Date("2021-12-31"))
> hl
[1] "2021-01-01" "2021-01-18" "2021-02-15" "2021-05-31" "2021-07-05" "2021-09-06" "2021-10-11" 
[8[ "2021-11-11" "2021-11-25"
> 
```

**Comment by wei-wu-nyc** [comment]
Thanks. Your are quick. I downloaded source and made the change and it is still compiling. Thanks for your quick reply.

Wei

**Comment by eddelbuettel** [comment]
Haha, I use `ccache` as a prefix to my compilers via `~/.R/Makeconf` (as I explained in a few places, _e.g._ [here](https://dirk.eddelbuettel.com/blog/2017/11/27/).  It _really_ helps with these big packages when only one out of N files changes.

**Comment by wei-wu-nyc** [comment]
My 2-liner changes worked as well. I will definitely check out how cache works.
Again, thanks a lot for your quick response and help.

Wei

**Comment by wei-wu-nyc** [comment]
I will check out how ccache works. Spellchecker changed it for me :-).

**Comment by eddelbuettel** [comment]
`ccache` is pretty genius. When added via `~/.R/Makeconf` as I do you _must_ also add two more settings to its config (as I say in my blog post) as R uses changing paths and may mess ctimes of files.  Then it is golden (if and when you re-run builds).

**Comment by eddelbuettel** [comment]
Added France too (per @wilsonfreitas earlier report).
