### ISSUE TITLE
Enum DayCounter 1 says Actual360FixEd but code uses Actual365Fixed

### ISSUE THREAD

**Issue by klin333** [eddelbuettel/rquantlib#156]
?RQuantLib::Enum shows DayCounter = 1 to mean "Actual360FixEd", but code src/utils.cpp line 69 of master shows QuantLib::Actual365Fixed() is returned if n==1

I guess that means the documentation is wrong?

I have RQuantLib 0.4.12 installed.

**Comment by eddelbuettel** [comment]
Thanks for catching that.  Maybe a documentation error.  Can you reference what you see in 'src/utiles.cpp line 69'?  One can fully reference this and when I look at that file I see something else:

https://github.com/eddelbuettel/rquantlib/blob/3b8ecb47135dd4e2144ad19d11c9acb94dad9d59/src/utils.cpp#L69

**Comment by eddelbuettel** [comment]
Oh I see, you meant _369_:  

https://github.com/eddelbuettel/rquantlib/blob/3b8ecb47135dd4e2144ad19d11c9acb94dad9d59/src/utils.cpp#L368-L369

I will fix the docs.

**Comment by eddelbuettel** [comment]
Thanks again!
