### ISSUE TITLE
access quantlib in c++ via RQuantLib?

### ISSUE THREAD

**Issue by klin333** [eddelbuettel/rquantlib#165]
I would like to create a new user package that uses QuantLib functionality in c++. It would be nice if I can access the QuantLib c++ functions via RQuantLib, because I don't want to deal with installation of QuantLib. I don't want to extend RQuantLib because I intend to do "user land" stuff that are specific to my application. 

However, I had no luck. Steps I took: initialise a package via `Rcpp::Rcpp.package.skeleton()`. Edit rcpp_hello_world.cpp as follows. Then edit DESCRIPTION to include `LinkingTo: Rcpp, RQuantLib`. 

```
#include <ql/quantlib.hpp>
#include <Rcpp.h>

using namespace Rcpp;

// [[Rcpp::depends(RQuantLib)]]


// [[Rcpp::export]]
double timesTwo(double x) {
  QuantLib::Calendar myCal = QuantLib::UnitedKingdom();
  return x;
}
```

Build fails with error
```
Error in LdFlags(FALSE) : Cannot supply LdFlags as none set.
Calls: source ... .pluginIncludes -> plugin -> plugin -> sprintf -> LdFlags
Execution halted
```

I see potentially useful stuff in R/inline.R but I couldn't make heads and tail of it... I was hoping for something similar to BH, RcppArmadillo which give user packages access to c++ libraries by simple installation of r packages instead of having to deal with c++ library installations.

**Comment by eddelbuettel** [comment]
> I would like to create a new user package that uses QuantLib functionality in c++

That requires linking. Full stop. You need `libquantlib.*` for whatever OS you use.

**Comment by klin333** [comment]
right. does that mean, if we want access to the full suite of c++ functions of QuantLib in an R package, we need to install QuantLib with this user package? For me, RcppQuantuccia exposed functionality is not enough. 

I think I'm after a RcppArmadillo type of workflow, where an R package exposes all the c++ functionality of a library, for use in another R package's c++ code. Any pointers on how to achieve this would be super appreciated. 

For example, this is useful when R users want to use QuantLib functionality in some ways that do not work with RQuantLib, yet it doesn't make sense to extend RQuantLib since these are user application specific operations.

**Comment by eddelbuettel** [comment]
I don't understand what the complexity is here.  Have you looked at what RQuantLib does and now?  

How is what you want to do different _other than that you wish you had this header-only_ ?  Well, sorry to be bearer of bad news: not every C++ library is header-only.

**Comment by eddelbuettel** [comment]
The RQuantLib repo is sorry to report that it can you help you with your desire to have all of QuantLib header-only. Life is tough sometimes, but we can only play the hands we are dealt.

**Comment by klin333** [comment]
ok, perfectly understand if this is out of scope. can close issue. 

But to clarify the complexity: let's say a user like me wants access to `QuantLib::FixedRateBond()` in c++ code. I am stuck. This is not exposed by RQuantLib to R, even if it is, I want to work in c++, not R. I believe the only way to get what I want is to handle the installation of QuantLib myself, which is fine I guess.

**Comment by eddelbuettel** [comment]
Sadly, yes. 

Look at any of the (cmdline) examples/ in QuantLib: they do just that.  A snipped of code, uses the headers _yet links against the whole library_.  I have the 20th anniversary of creating RQuantLib coming and trust me when I say: I hear your pain.  But hey QuantLib is still free.

So what you want to do in a nutshell is to have 'twin' of RQuantLib with just "your" bond pricer.  In practice, you still need all the hand-holding we already have for parameters in/out, R Dates to QuantLib dates and back etc ... so  that "net net" it is probably still easiest for you to "just" contribute a new routine to RQuantLib.  But by all means: explore your options.  But "wishing for header-only" alone sadly does not make it so.  Sorry mate.

**Comment by klin333** [comment]
ok, turned out incorporating QuantLib c++ library to a user R package wasn't too hard. Just copy these files from the rquantlib repo to your own package: src/Makevars.in, src/Makevars.win, tools/winlibs.R 

I got this simple method to work in Windows, and it probably only works for Windows. Since it's simple to just install QuantLib, I no longer see the need for a header only R package for QuantLib
