### ISSUE TITLE
Implied vol of a binary european option doesn't converge 

### ISSUE THREAD

**Issue by wklm** [eddelbuettel/rquantlib#170]
```{r}
RQuantLib::BinaryOptionImpliedVolatility(
  type = "call",
  value = 5.1164,
  underlying = 28,
  strike = 65,
  dividendYield = 0,
  riskFreeRate = 0,
  maturity = 218/365,
  volatility = .83,
  cashPayoff = 100
)
```

results in:  
```
Error in binaryOptionImpliedVolatilityEngine(type, value, underlying,  : 
  root not bracketed: f[1e-07,4] -> [-5.116400e+00,-1.663857e+00]
```

while `83%` is exactly the implied vol of this option

**Comment by eddelbuettel** [comment]
My first instinct is always for corner conditions in parameters so maybe try with a really small, but non-zero, rate and divididend yields.

**Comment by wklm** [comment]
Thanks @eddelbuettel, I'll follow up with them. Let's hope it's fixed in one of the future Quantlib releases. This issue here can be closed.
Cheers!
