### ISSUE TITLE
trouble installing RQuantLib on AWS EC2 linux

### ISSUE THREAD

**Issue by jrschwartz** [eddelbuettel/rquantlib#172]
I am unable to install the RQuantLib package.
I have attached the log below
Please help

* installing *source* package ‘RQuantLib’ ...
** package ‘RQuantLib’ successfully unpacked and MD5 sums checked
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -m64 -std=gnu++11 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -m64 -std=gnu++11 accepts -g... (cached) yes
checking for R... yes
checking for quantlib-config... yes
checking for Boost development files... yes
checking for minimal Boost version... yes
configure: creating ./config.status
config.status: creating src/Makevars
Configured RQuantlib 0.4.16
** libs
g++ -m64 -std=gnu++11 -I"/usr/include/R" -DNDEBUG  -I'/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/Rcpp/include' -I/usr/local/include  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic  -I/usr/local/include -fpermissive -I../inst/include -I. -DBOOST_NO_AUTO_PTR -fopenmp -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches    -m64 -mtune=generic  -c RcppExports.cpp -o RcppExports.o
{standard input}: Assembler messages:
{standard input}: Warning: end of file not at end of a line; newline inserted
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <http://bugzilla.redhat.com/bugzilla> for instructions.
make: *** [RcppExports.o] Error 4
ERROR: compilation failed for package ‘RQuantLib’
* removing ‘/home/ec2-user/R/x86_64-koji-linux-gnu-library/4.0/RQuantLib’

The downloaded source packages are in
        ‘/tmp/Rtmp5Ow4NP/downloaded_packages’
Warning message:
In install.packages("RQuantLib") :
  installation of package ‘RQuantLib’ had non-zero exit status

**Comment by eddelbuettel** [comment]
This is a recurrent error we also see with small VMs and alike -- increase your RAM allocation and you will be fine. This is complex C++ code and it stretches the compiler.

(Easier still:  Use Ubuntu and use the pre-made binary I provide...)

**Comment by eddelbuettel** [comment]
I'll close this.  If you have a persistent error _when proper resources are allocated_ please feel free to reopen but I am fairly certain that you "simply" starved the compiler off sufficient resources.
