### ISSUE TITLE
RQuantlib compilation issues in windows

### ISSUE THREAD

**Issue by edult** [eddelbuettel/rquantlib#39]
I am trying to get RQuantlib installed from the source, primarily to be able to call further functions from the Quantlib library using Rcpp.

Here is my R session Info

```
> sessionInfo()
R version 3.2.4 (2016-03-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252    LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                            LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.4
```

I got my own build of  of Quantlib and boost

Here is how my RQuantLib\src\Makevars.win after the changes

```
QUANTLIB_ROOT=C:/temp/QuantLib-1.7.1
BOOSTLIB=C:/temp/boost_1_60_0

PKG_CPPFLAGS=-I$(QUANTLIB_ROOT) -I../inst/include -I. -I$(BOOSTLIB) -DQL_PACKAGE_VERSION=1.7.1
PKG_CXXFLAGS=$(SHLIB_OPENMP_CFLAGS) -fpermissive
PKG_LIBS=-L$(QUANTLIB_ROOT)/lib${R_ARCH} -L$(BOOSTLIB)/stage/lib  -lQuantLib $(SHLIB_OPENMP_CFLAGS)
```

Unfortunately I am having some issues while building RQuantlib. There is quite a long log, I adding beginning and the end.

```
$ "C:\Program Files\R\R-3.2.4\bin\x64\R" CMD INSTALL RQuantLib

* installing to library 'C:/Program Files/R/R-3.2.4/library'

* installing *source* package 'RQuantLib' 

files 'src/Makevars.win', 'src/utils.cpp' have the wrong MD5 checksums


   **********************************************

   WARNING: this package has a configure script

         It probably needs manual configuration

   **********************************************

** libs

cygwin warning:
  MS-DOS style path detected: C:/PROGRA~1/R/R-32~1.4/etc/x64/Makeconf
  Preferred POSIX equivalent is: /cygdrive/c/PROGRA~1/R/R-32~1.4/etc/x64/Makeconf
  CYGWIN environment variable option "nodosfilewarning" turns off this warning.
  Consult the user's guide for more details about POSIX paths:
    http://cygwin.com/cygwin-ug-net/using.html#using-pathnames
g++ -m64 -shared -s -static-libgcc -o RQuantLib.dll tmp.def RcppExports.o asian.o barrier_binary.o bermudan.o bonds.o calendars.o curves.o dates.o daycounter.o discount.o hullwhite.o implieds.o modules.o schedule.o utils.o vanilla.o zero.o -LC:/temp/QuantLib-1.7.1/lib/x64 -LC:/temp/boost_1_60_0/stage/lib -lQuantLib -fopenmp -Ld:/RCompile/r-compiling/local/local323/lib/x64 -Ld:/RCompile/r-compiling/local/local323/lib -LC:/PROGRA~1/R/R-32~1.4/bin/x64 -lR
RcppExports.o:RcppExports.cpp:(.text+0x232): undefined reference to `boost::assertion_failed(char const*, char const*, char const*, long)'

RcppExports.o:RcppExports.cpp:(.text+0x323): undefined reference to `boost::assertion_failed(char const*, char const*, char const*, long)'

RcppExports.o:RcppExports.cpp:(.text$_ZN8QuantLib15SegmentIntegralD1Ev[_ZN8QuantLib15SegmentIntegralD1Ev]+0x3): undefined reference to `vtable for QuantLib::Integrator'

RcppExports.o:RcppExports.cpp:(.text$_ZN8QuantLib15SegmentIntegralD0Ev[_ZN8QuantLib15SegmentIntegralD0Ev]+0x3): undefined reference to `vtable for QuantLib::Integrator'


--------------------------------

zero.o:zero.cpp:(.text+0x4590): more undefined references to `boost::assertion_failed(char const*, char const*, char const*, long)' follow

zero.o:zero.cpp:(.text$_ZN8QuantLib21InterpolatedZeroCurveINS_5CubicEEC2EjRKNS_8CalendarERKNS_10DayCounterERKSt6vectorINS_6HandleINS_5QuoteEEESaISC_EERKS9_INS_4DateESaISH_EERKS1_[_ZN8QuantLib21InterpolatedZeroCurveINS_5CubicEEC2EjRKNS_8CalendarERKNS_10DayCounterERKSt6vectorINS_6HandleINS_5QuoteEEESaISC_EERKS9_INS_4DateESaISH_EERKS1_]+0xd0): undefined reference to `QuantLib::ZeroYieldStructure::ZeroYieldStructure(unsigned int, QuantLib::Calendar const&, QuantLib::DayCounter const&, std::vector<QuantLib::Handle<QuantLib::Quote>, std::allocator<QuantLib::Handle<QuantLib::Quote> > > const&, std::vector<QuantLib::Date, std::allocator<QuantLib::Date> > const&)'

zero.o:zero.cpp:(.text$_ZN8QuantLib21InterpolatedZeroCurveINS_5CubicEEC2EjRKNS_8CalendarERKNS_10DayCounterERKSt6vectorINS_6HandleINS_5QuoteEEESaISC_EERKS9_INS_4DateESaISH_EERKS1_[_ZN8QuantLib21InterpolatedZeroCurveINS_5CubicEEC2EjRKNS_8CalendarERKNS_10DayCounterERKSt6vectorINS_6HandleINS_5QuoteEEESaISC_EERKS9_INS_4DateESaISH_EERKS1_]+0x18c): undefined reference to `QuantLib::Date::Date()'

zero.o:zero.cpp:(.text$_ZN8QuantLib6HandleINS_5QuoteEEC2ERKN5boost10shared_ptrIS1_EEb[_ZN8QuantLib6HandleINS_5QuoteEEC2ERKN5boost10shared_ptrIS1_EEb]+0x297): undefined reference to `QuantLib::Observable::notifyObservers()'

collect2: ld returned 1 exit status

no DLL was created

ERROR: compilation failed for package 'RQuantLib'
```

What do you think is causing this? My boost build is using static libs

Thanks

**Comment by eddelbuettel** [comment]
RQuantLib can be a bit of a beast, particularly on Windows.    

Concerning the build infrastructure, for the last little while, @jeroenooms (with help from @thirdwing) provided what CRAN uses from [this GH repo](https://github.com/rwinlib/quantlib) which CRAN's windows builds use too.  I think your easiest bet would be to just switch to using this.  It should work with RQuantLib out of the box.

As for why your builds failed, static builds of Boost may be a cause. I think we only ever used dynamic builds.  I mostly live on Linux only and don't have these issues.

We could rope in a few more helpers if you get stuck but your best bet may be this prebuilt library of QuantLib.

**Comment by tleitch** [comment]
It got all the way to ld, so the the compile worked. I'm building on windows with a precompiled version of Quantlib. Looking at your Makevars.win, except for location, pretty much similar (ignoring location differences) except I do not have the last line's entry "-L$(BOOSTLIB)/stage/lib".

**Comment by thirdwing** [comment]
I am afraid I am not helping to build that. I think all repos in rwinlib are compiled on Windows and I prefer cross-compiling.

It will easier for us to find the problem if you can provide more info, including which Rtools you are using and how you compiled the QuantLib.

**Comment by eddelbuettel** [comment]
@tleitch Historically we have _always_ bundled Boost along with QuantLib because the latter is so dependent on the former.

@tleitch Acknowledged, and good point regarding the tools.  It is best to use _exactly_ what R uses, ie the Rtools binaries.

**Comment by tleitch** [comment]
Perhaps the load failed due to conflicts between Boost included in Rquantlib and the library on the load line? I only need the boost headers for the compile but do not need the boost library at load.

**Comment by edult** [comment]
-I am on RTools 3.1.0.1942
-I have build Quantlib with visual studio. I tried static and dynamic version of Quantlib, they both fail; though static fails with some additional issues
-Yes all objects compile, it is the final link is the issue. It is not able to find some references
-I added Boost Library since I was thinking it is looking at boost compiled objects -L$(BOOSTLIB)/stage/lib @tleitch are you saying that is not needed, is it enough to just have headers

**Comment by eddelbuettel** [comment]
Let's stop right here:

> I have built Quantlib with visual studio.

That is a a (grave) misunderstanding on your part. You (very generally speaking) simply cannot mix C++ code from different compilers _as they generate different function signatures_ leading to your linking issue.  That is _why_ we point you to what CRAN uses.  Makes your life easier -- all of QuantLib prebuild -- and works.  So I will close this -- no issue with with the package.  

As for your last question:  I think only the Boost testing library needs to be linked in if you plan on using the test suite.  Else it is all headers.
