### ISSUE TITLE
Some date generation rules are missing

### ISSUE THREAD

**Issue by thrasibule** [eddelbuettel/rquantlib#52]
oldCDS and CDS are missing see https://github.com/lballabio/QuantLib/blob/master/ql/time/dategenerationrule.hpp#L59. These are useful for generating cds schedules. Incidentally, this would come for free with pr #50 (modulo updating the docs).

**Comment by eddelbuettel** [comment]
Seems reasonable -- they probably got added QL since we first carried this over 10+ years ago. 

Would be nice to also have a use case, test function, example in the help file etc pp
