### ISSUE TITLE
SABR Swaption Module

### ISSUE THREAD

**Issue by tleitch** [eddelbuettel/rquantlib#59]
A SABR module that uses the vol cube for european swaptions with an option to use the same surface for Bermudan swaptions would be useful.

**Comment by tleitch** [comment]
I'm near completion of sabr.R and have a volcube for the example that has ~1400 data points. Is there somewhere optimal to put this on the web, say, github, for user access?

**Comment by eddelbuettel** [comment]
Yes, I can help you with this. 

Every GitHub repo has an associated web presence one can enable via the `gh-pages` branch.

**Comment by eddelbuettel** [comment]
Done via #60.
