### ISSUE TITLE
Serializing object 

### ISSUE THREAD

**Issue by sonben** [eddelbuettel/rquantlib#81]
I have just started to access rquantlib from sql server. One feature that would be particularly useful is for rquantlib to replicate the quantlibxl ohobjectload and ohobjectsave. This serialize the quantlib object in xml. This would allow the modlling to be done in excel and object transportable to rquantlib.

I dont really know what happens under the covers, but object serialization in this way may open up rquantlib to more of the quantlib library without having to support the interface.

I do know that R has its own serialization features,  but it is native binary. Ok to work with but not transportable b/w different systems.

**Comment by student-t** [comment]
I don't think this makes sense because RQuantLib is really like a financial recipes.

**Comment by eddelbuettel** [comment]
RQuantLib is a moderately simple shell around QuantLib.  Now, QuantLib has what you ask for in the [Reposit Project](http://quantlib.org/reposit/) but getting that over here is a (big) project in and by itself. 

So nothing immediately tangible for us, and I close this.
