### ISSUE TITLE
QuantLib NPV Function

### ISSUE THREAD

**Issue by FrozenQuant** [eddelbuettel/rquantlib#82]
I am doing some research into problems involving insurance or pension liabilities and was wondering if there is a way to value an irregular set of actuarially determined cash flows using RQuantLib.   These would be non-coupon bearing cash flows with amounts specified by date.   QuantLib would be an ideal route for me because it would be possible to have consistent valuation of fixed income instruments and my calculated liabilities.

I can see there are NPV functions in QuantLib's CashFlows class but I was wondering if any of them are directly available in RQuantLib.   Any thoughts on accessing these would be appreciated.

**Comment by eddelbuettel** [comment]
If you are capable of reading the C++ code in QuantLib and work with its examples, you should be able to build on existing examples for extending RQuantLib along this route -- ie accessing these NPV calculations.

Getting R dates to QL may change a little as we just started with a new datevector class in Rcpp, but it won't fundamentally change:  have a date in R, get it to QL, do computations, calculations, transformations, ... on it and return dates do all work and will work -- but just saying that there _may_ be small changes.  We always try to keep APIs stable but it can't always be guaranteed.

**Comment by FrozenQuant** [comment]
Thanks for the reply.  Just to be sure, you're suggesting working out the process in C++ then moving to RCpp to provide access from R?

**Comment by eddelbuettel** [comment]
Yes, exactly.  Having a C++ solution gets you an "existence proof" and you can then work out how to access it from.  Classic separation of concerns -- works for me.

**Comment by theyuish** [comment]
I am keen to contribute to RQuantlib too - just wonder if there is more guidance how to APIs to Quantlib (using the same methodology RQuantlib use) and create an new function on R. I've Rcpp experience.

**Comment by eddelbuettel** [comment]
Yes, yes and yes.

A common approach is to take a (QuantLib) function you like, mayne find its unit test to get a self contained invocation, and then just wrap some Rcpp glue around it.  

There is nothing automated or magic.   Also, may be prudent to just discuss this in an issue ticket here first just to avoid doubling work (someoone else might be sitting on something partially done) and to discuss any particular aspects or ideas.

**Comment by theyuish** [comment]
Thanks @eddelbuettel. I'm sure someone must have done it but I am thinking to do a pricing engine for FX products from market calibration (interest rates and volatility curves) to the final prices (such as the functions you have done, EuropeanOption etc).

**Comment by eddelbuettel** [comment]
Sounds good.  I don't think we have that.  Fixed Income got an update last year; there may be examples with curves.   I made Datevectors a little better in Rcpp in the meantime, but RQuantLib basically always did its own thing.

**Comment by eddelbuettel** [comment]
Closing for lack of follow-up.
