### ISSUE TITLE
Window Binary Version is 0.4.2？

### ISSUE THREAD

**Issue by huihuibear** [eddelbuettel/rquantlib#83]
I installed the windows binary version following the instructions on this site but it's version 0.4.2 instead of 0.4.3?

**Comment by eddelbuettel** [comment]
This suggestes 0.4.3:  https://github.com/ghrr/drat/tree/gh-pages/bin/windows/contrib/3.3

**Comment by eddelbuettel** [comment]
Please demonstrate with a *reproducible example* that this does not work, rather than randomly spraying issue tickets in other places.

**Comment by eddelbuettel** [comment]
It works as documented:

```
R> drat::addRepo("ghrr")
R> options("repos")
$repos
                          CRAN                           ghrr 
 "https://cloud.r-project.org" "https://ghrr.github.io/drat/" 

R> install.packages("RQuantLib", type="binary")
Installing package into 'c:/opt/R-library'
(as 'lib' is unspecified)
trying URL 'https://ghrr.github.io/drat/bin/windows/contrib/3.3/RQuantLib_0.4.3.zip'
Content type 'application/zip' length 7993848 bytes (7.6 MB)
downloaded 7.6 MB

package 'RQuantLib' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\xxxxxxxxxxxx\AppData\Local\Temp\RtmpAHvBmo\downloaded_packages
R> 
```

**Comment by huihuibear** [comment]
Thanks you for the reply but when I did that it still installed 0.4.2:
> drat::addRepo("ghrr")
> options("repos")
$repos
                                CRAN                            CRANextra                                 ghrr 
         "https://cran.rstudio.com/" "http://www.stats.ox.ac.uk/pub/RWin"       "https://ghrr.github.io/drat/" 
attr(,"RStudio")
[1] TRUE

> install.packages("RQuantLib", type="binary")
Error in install.packages : Updating loaded packages

Restarting R session...

> install.packages("RQuantLib", type = "binary")
Installing package into ‘C:/Users/hwang2/Documents/R/win-library/3.2’
(as ‘lib’ is unspecified)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/RQuantLib_0.4.2.zip'
Content type 'application/zip' length 8356524 bytes (8.0 MB)
downloaded 8.0 MB

package ‘RQuantLib’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\XXXXXXXX\AppData\Local\Temp\Rtmp27fMXN\downloaded_packages

**Comment by eddelbuettel** [comment]
Because you are on outdated version of R itself:

> Installing package into ‘C:/Users/hwang2/Documents/R/win-library/3.2’ 

it follows

> trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/RQuantLib_0.4.2.zip'

Use R 3.3.* and it will work.

**Comment by huihuibear** [comment]
Oh I see. Thanks a lot!
