### ISSUE TITLE
how to install rquantlib without online connectivity from R

### ISSUE THREAD

**Issue by randomgambit** [eddelbuettel/rquantlib#85]
Hello @eddelbuettel ,

Amazing work! I would like to use this package but my environment is behind a strict firewall and I cannot use

```
drat::addRepo("ghrr")       #  maybe use 'install.packages("drat")' first 
install.packages("RQuantLib", type="binary")
```

to get the package. Indeed, connectivity from within a program is prohibited. I can download stuff manually however (how bizarre this might seem when you think about it)

 Is there any possibility of downloading manually the binaries from somewhere, and then install it manually from Rstudio 3.3.2?

Thanks!!

**Comment by eddelbuettel** [comment]
Of course.  Download the file by hand.  Use `install.packages()`, or `R CMD INSTALL ...` on the commandline.

**Comment by randomgambit** [comment]
@eddelbuettel it worked indeed! can I ask yo a quick follow up? Is there a tutorial somewhere about rquantlib? The manual is pretty thick and I dont see any vignette on github.

**Comment by randomgambit** [comment]
@eddelbuettel in particular, I am interested in backing up the yield-to-maturity every day for a fixed rate bond, given the required inputs (coupons, maturity, clean price). Can you please tell me what would be the correct syntax here?

**Comment by randomgambit** [comment]
@eddelbuettel my bad https://rdrr.io/cran/RQuantLib/man/FixedRateBond.html
