### ISSUE TITLE
Error in AffineSwaption ... could not find function "AffineSwaption"

### ISSUE THREAD

**Issue by dado0583** [eddelbuettel/rquantlib#87]
Hi. I don't know if this is an issue or not but I struggled to find somewhere I could find the answer and am still a bit of a n00b to R. I installed RQuantLib (but not the QuantLib C++ libraries themselves), and when I run through the AffineSwaption example I get the following error message:

```
> Error in AffineSwaption(params, dcurve, swaptionMaturities, swapTenors,  : 
>   could not find function "AffineSwaption"
```

Does QuantLib C++ libraries get installed when I intall RQuantLib or do I need to install separately? And is this a real issue, or is this a user error?

**Comment by eddelbuettel** [comment]
> but not the QuantLib C++ libraries themselves

That won't work.

> do I need to install separately?

Yes.
