### ISSUE TITLE
function isHoliday(), isBusinessDay doesn't give the right result.

### ISSUE THREAD

**Issue by XuXin09** [eddelbuettel/rquantlib#88]
Hi, first thanks for developing this package, I've tried a lot to remove the holidays between two dates and finally made it with this package.

However,  the result of `isHoliday()`, `isBusinessDay()` doesn't show the right result. So my function of counting business days always got some errors. 

I checked and found that, 
Feb 2, 2017(Thursday) is Chinese New Year Holiday in China, but the function result said it' s a business day.
```
isBusinessDay("China",2017-02-02)
[1] TRUE
isHoliday("China",2017-02-02)
[1] FALSE
```
Feb 4, 2017(Saturday) is a workday after the Chinese New Year, but the function result said it' s a holiday.
```
isBusinessDay("China",2017-02-04)
[1] FALSE
isHoliday("China",2017-02-04)
[1] TRUE
```
I just guess maybe the calendar hasn't been updated in-time from QuantLib.  Thank you.

**Comment by eddelbuettel** [comment]
That is very likely.  Chinese holidays appear to be "hard-wired" rather than computed.  

Can you please check if QuantLib has this correct, eg by checking with [this china.cpp file](https://github.com/lballabio/QuantLib/blob/master/ql/time/calendars/china.cpp) ?

**Comment by eddelbuettel** [comment]
Make sure you have QuantLib 1.10 as the underlying library:

```r
R> library(RQuantLib)
R> getQuantLibVersion()
[1] "1.10"
R> isBusinessDay("China", as.Date("2017-02-02") + 0:2)
[1] FALSE  TRUE FALSE
R> isHoliday("China", as.Date("2017-02-02") + 0:2)
[1]  TRUE FALSE  TRUE
R> 
```
