### ISSUE TITLE
Problem with DiscountCurve

### ISSUE THREAD

**Issue by jaheskje** [eddelbuettel/rquantlib#93]
Hi!
When reading about the function DiscountCurve in the discountcurve.RD it says that as input it can use tsQutes 1:10 year swap. In version 0.4.2. it was only possible to have a subset of this (1-year, 3-year, 5-year).

When installing the package from CRAN this functionality isn't provided in the RQuantLib_0.4.2.Zip (NOTE: Not version 0.4.3. but the only file that worked installing)

If we try the RQuantLib_0.4.3.tar.gx we get a massage along "installation of package 'path' had non-zero exit status"

This is on R-version 3.4.1 in RStudio 1.0.44

**Comment by eddelbuettel** [comment]
You are missing the part where you first compile QuantLib from its source into library used by RQuantLib.
