### ISSUE TITLE
Installation on EC2 Ubuntu issues

### ISSUE THREAD

**Issue by GoChartingAdmin** [eddelbuettel/rquantlib#94]
Hi,

I have followed 2 ways to install QuantLib in my AWS EC2 Ubuntu instance

1.  [Install QuantLib - Method 1](http://quantlib.org/install/linux.shtml)
2.  Install QuantLib - Part II - sudo apt-get install libquantlib0 libquantlib0-dev

However, now when I run install.packages("RQuantLib") , I get the following error

```
g++ -I/usr/share/R/include -DNDEBUG   -I"/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -I/usr/include -fpermissive -I../inst/include -I. -fopenmp -fpic  -g -O2 -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g  -c RcppExports.cpp -o RcppExports.o
g++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
make: *** [RcppExports.o] Error 4
ERROR: compilation failed for package ‘RQuantLib’
* removing ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.2/RQuantLib’
Warning in install.packages :
  installation of package ‘RQuantLib’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpoR3ft2/downloaded_packages’
```

Need help

Regards
SD

**Comment by eddelbuettel** [comment]
You need more RAM.  Or, if you want to it cheaply and have infinite time, more swapspace.

This package is a beast to compile.  If you can use the binaries (which are in Ubuntu), do.

**Comment by GoChartingAdmin** [comment]
2 additional queries:
1. How much swapspace should I add.  I run a 512MB t2.nano instance of EC2
2. Can you help me with the code that I can use to run the Ubuntu binaries
