### ISSUE TITLE
EuropeanOption produces wrong price

### ISSUE THREAD

**Issue by Aiwiosh** [eddelbuettel/rquantlib#97]
For example EuropeanOption("put",100,100,0.0,0.0,0.02,0.4) returns 2.2249. This is wrong. The correct value of a put option under the Black-Scholes Model with maturity 0.02, strike=100, underlying=100, zero dividends and zero interest rates is 2.256457. The Difference is about 1.4%.

**Comment by eddelbuettel** [comment]
You may have your maturity scaling wrong.  0.02 of ... what?  255? 252? 365?

QL is over fifteen years old.  There are a bazillion unit tests in it.  Black-Scholes just like other prices is tested against a bazillion published results.  You need to do better to back up an error (eg reproducible would help). 

Also: what version?  I *do* get 2.2565.

```r
R> library(RQuantLib)
R> EuropeanOption("put", 100, 100, 0, 0, 0.02, 0.4)
Concise summary of valuation for EuropeanOption 
   value    delta    gamma     vega    theta      rho   divRho 
  2.2565  -0.4887   0.0705   5.6396 -56.3964  -1.0226   0.9774 
R> packageVersion("RQuantLib")
[1] ‘0.4.4’
R> 
```
